/**
 * Bill Splitter - Professional Clean Glass UI Logic & State Engine
 */

// Application State
let state = {
    people: [],
    items: [],
    extras: {
        taxPercent: 0,
        servicePercent: 0,
        discountAmount: 0
    },
    settings: {
        language: 'en',
        darkMode: true
    },
    personIdCounter: 1,
    itemIdCounter: 1
};

// Bilingual Dictionary
const i18n = {
    en: {
        title: "Bill Splitter",
        subtitle: "Smart group expense & grocery calculator",
        btn_reset: "Reset",
        theme_light: "Light",
        theme_dark: "Dark",
        step1: "Shoppers & Friends",
        step1_desc: "Add everyone splitting this bill",
        person_ph: "Enter name (e.g. Ali)",
        btn_add_person: "Add",
        no_people_yet: "No shoppers added yet. Enter names above.",
        step2: "Add Item / Expense",
        step2_desc: "Specify price and who shares it",
        item_ph: "Item name (e.g. Apples, Pizza)",
        price_ph: "0.00",
        share_label: "Who shares this item?",
        select_all: "Select All",
        clear_all: "Clear",
        empty_people: "Please add shoppers first.",
        btn_add_item: "Add to Bill",
        step3: "Bill & Breakdown",
        step3_desc: "Live itemized receipt & splits",
        no_items_yet: "Receipt is empty. Add items from the left panel.",
        tax_discount_title: "Tax, Service & Discount",
        label_tax: "SST / Tax (%)",
        label_service: "Service Fee (%)",
        label_discount: "Discount (RM)",
        subtotal: "Subtotal:",
        total_receipt: "Grand Total:",
        individual_splits: "Who Owes What",
        click_to_view_detail: "Click on any person to inspect itemized breakdown",
        step4: "Share & Export",
        step4_desc: "Send receipt to friends or copy breakdown",
        btn_wa: "WhatsApp",
        btn_copy: "Copy Text",
        btn_qr: "QR Code",
        qr_desc: "Scan with camera to read complete receipt:",
        close: "Close",
        modal_subtotal: "Items Share:",
        modal_extra: "Tax & Fees Share:",
        modal_final: "Total to Pay:",
        items_count: "items",
        item_count: "item",
        pays: "pays",
        shared_by: "shared by",
        unnamed_item: "Item",
        toast_person_added: "Shopper added successfully!",
        toast_person_removed: "Shopper removed.",
        toast_person_in_use: "Cannot delete: This person is sharing items in the bill!",
        toast_enter_name: "Please enter a valid name.",
        toast_name_exists: "A shopper with this name already exists.",
        toast_item_added: "Item added to receipt!",
        toast_item_deleted: "Item removed.",
        toast_need_people: "Please add at least one person first.",
        toast_invalid_price: "Please enter a valid item price greater than 0.",
        toast_select_shopper: "Please select at least one person who shares this item.",
        toast_copied: "Receipt summary copied to clipboard!",
        toast_no_items: "Please add some items to your bill first!",
        toast_reset_confirm: "Are you sure you want to reset everything? All data will be cleared.",
        receipt_header: "🛒 *BILL SPLITTER RECEIPT*",
        receipt_items_title: "📋 *Items:*",
        receipt_breakdown_title: "👥 *Who Owes What:*",
        receipt_footer: "Generated by Bill Splitter",
        tab_by_items: "By Items",
        tab_by_buyers: "What Each Buyer Bought",
        empty_buyers_hint: "Add shoppers and items to see what each person bought.",
        copy_buyer_bill: "Copy Bill",
        wa_buyer_bill: "WhatsApp",
        no_items_bought: "Has not shared any items yet",
        buyer_bill_copied: "Bill copied!",
        tax_fee_share: "Tax & Fees:"
    },
    ms: {
        title: "Split Bil",
        subtitle: "Kiraan barang dapur & perbelanjaan kumpulan",
        btn_reset: "Padam Semua",
        theme_light: "Cerah",
        theme_dark: "Gelap",
        step1: "Senarai Rakan & Pembeli",
        step1_desc: "Tambah semua orang yang berkongsi bil ini",
        person_ph: "Masukkan nama (cth: Ali)",
        btn_add_person: "Tambah",
        no_people_yet: "Tiada pembeli lagi. Masukkan nama di atas.",
        step2: "Tambah Barang / Belanja",
        step2_desc: "Tetapkan harga dan siapa yang kongsi",
        item_ph: "Nama barang (cth: Epal, Pizza)",
        price_ph: "0.00",
        share_label: "Siapa kongsi barang ni?",
        select_all: "Pilih Semua",
        clear_all: "Kosongkan",
        empty_people: "Sila tambah nama orang dahulu.",
        btn_add_item: "Tambah Dalam Resit",
        step3: "Resit & Kiraan",
        step3_desc: "Rumusan bil & pecahan bayaran langsung",
        no_items_yet: "Resit kosong. Tambah barang dari panel sebelah.",
        tax_discount_title: "Cukai, Servis & Diskaun",
        label_tax: "SST / Cukai (%)",
        label_service: "Caj Servis (%)",
        label_discount: "Diskaun (RM)",
        subtotal: "Jumlah Kasar:",
        total_receipt: "Jumlah Keseluruhan:",
        individual_splits: "Bahagian Perlu Dibayar",
        click_to_view_detail: "Tekan mana-mana nama untuk lihat pecahan barang",
        step4: "Kongsi & Eksport",
        step4_desc: "Hantar resit kepada rakan atau salin teks",
        btn_wa: "WhatsApp",
        btn_copy: "Salin Teks",
        btn_qr: "Kod QR",
        qr_desc: "Imbas dengan kamera untuk baca resit penuh:",
        close: "Tutup",
        modal_subtotal: "Bahagian Barang:",
        modal_extra: "Bahagian Caj & Cukai:",
        modal_final: "Jumlah Bayaran:",
        items_count: "barang",
        item_count: "barang",
        pays: "perlu bayar",
        shared_by: "dikongsi",
        unnamed_item: "Barang",
        toast_person_added: "Nama berjaya ditambah!",
        toast_person_removed: "Nama berjaya dipadam.",
        toast_person_in_use: "Tak boleh padam! Nama ini ada dalam perkongsian barang di resit.",
        toast_enter_name: "Sila masukkan nama yang sah.",
        toast_name_exists: "Nama ini sudah ada dalam senarai.",
        toast_item_added: "Barang ditambah ke dalam resit!",
        toast_item_deleted: "Barang dipadam.",
        toast_need_people: "Sila tambah nama orang terlebih dahulu.",
        toast_invalid_price: "Sila masukkan harga yang sah melebihi 0.",
        toast_select_shopper: "Sila tandakan sekurang-kurangnya seorang yang berkongsi barang ini.",
        toast_copied: "Rumusan resit berjaya disalin ke papan klip!",
        toast_no_items: "Sila tambah barang dahulu!",
        toast_reset_confirm: "Adakah anda pasti mahu memadam semua data?",
        receipt_header: "🛒 *RESIT SPLIT BIL*",
        receipt_items_title: "📋 *Senarai Barang:*",
        receipt_breakdown_title: "👥 *Bahagian Perlu Dibayar:*",
        receipt_footer: "Dikira oleh Aplikasi Split Bil",
        tab_by_items: "Mengikut Barang",
        tab_by_buyers: "Apa Setiap Pembeli Beli",
        empty_buyers_hint: "Tambah pembeli dan barang untuk melihat pecahan setiap orang.",
        copy_buyer_bill: "Salin Bil",
        wa_buyer_bill: "WhatsApp",
        no_items_bought: "Belum berkongsi sebarang barang",
        buyer_bill_copied: "Bil berjaya disalin!",
        tax_fee_share: "Cukai & Caj:"
    }
};

// DOM Elements
const inputPerson = document.getElementById('input-person');
const btnAddPerson = document.getElementById('btn-add-person');
const peopleBadges = document.getElementById('people-badges');
const emptyPeopleHint = document.getElementById('empty-people-hint');
const peopleCountEl = document.getElementById('people-count');

const inputItemName = document.getElementById('item-name');
const inputItemPrice = document.getElementById('item-price');
const btnAddItem = document.getElementById('btn-add-item');
const dynamicCheckboxes = document.getElementById('dynamic-checkboxes');
const btnSelectAll = document.getElementById('btn-select-all');
const btnClearAll = document.getElementById('btn-clear-all');

const itemList = document.getElementById('item-list');
const emptyItemsState = document.getElementById('empty-items-state');
const itemsCountEl = document.getElementById('items-count');

// Buyer breakdown & Tab elements
const tabBtnItems = document.getElementById('tab-btn-items');
const tabBtnBuyers = document.getElementById('tab-btn-buyers');
const viewItems = document.getElementById('view-items');
const viewBuyers = document.getElementById('view-buyers');
const buyersBreakdownList = document.getElementById('buyers-breakdown-list');
const emptyBuyersState = document.getElementById('empty-buyers-state');

const btnToggleExtras = document.getElementById('btn-toggle-extras');
const extrasPanel = document.getElementById('extras-panel');
const extrasArrow = document.getElementById('extras-arrow');
const inputTax = document.getElementById('input-tax');
const inputService = document.getElementById('input-service');
const inputDiscount = document.getElementById('input-discount');

const subTotalEl = document.getElementById('sub-total');
const grandTotalEl = document.getElementById('grand-total');
const rowTax = document.getElementById('row-tax');
const taxAmountEl = document.getElementById('tax-amount');
const rowService = document.getElementById('row-service');
const serviceAmountEl = document.getElementById('service-amount');
const rowDiscount = document.getElementById('row-discount');
const discountAmountEl = document.getElementById('discount-amount');

const debtCardsContainer = document.getElementById('debt-cards-container');

const btnLang = document.getElementById('btn-lang');
const langFlag = document.getElementById('lang-flag');
const langText = document.getElementById('lang-text');
const btnTheme = document.getElementById('btn-theme');
const themeIcon = document.getElementById('theme-icon');
const themeText = document.getElementById('theme-text');
const btnReset = document.getElementById('btn-reset');

const btnWa = document.getElementById('btn-whatsapp');
const btnCopy = document.getElementById('btn-copy');
const btnQr = document.getElementById('btn-generate-qr');
const qrContainer = document.getElementById('qr-container');
const qrImage = document.getElementById('qr-image');
const btnCloseQr = document.getElementById('btn-close-qr');

const modalBreakdown = document.getElementById('modal-breakdown');
const modalPersonName = document.getElementById('modal-person-name');
const modalAvatar = document.getElementById('modal-avatar');
const modalItemsList = document.getElementById('modal-items-list');
const modalSubtotalVal = document.getElementById('modal-subtotal-val');
const modalTaxLine = document.getElementById('modal-tax-line');
const modalExtraVal = document.getElementById('modal-extra-val');
const modalFinalVal = document.getElementById('modal-final-val');
const btnCloseModal = document.getElementById('btn-close-modal');
const btnDismissModal = document.getElementById('btn-dismiss-modal');

const toastContainer = document.getElementById('toast-container');

// Local Storage Management
function saveToStorage() {
    try {
        localStorage.setItem('bill_splitter_state', JSON.stringify(state));
    } catch (e) {
        console.warn('LocalStorage error:', e);
    }
}

function loadFromStorage() {
    try {
        const saved = localStorage.getItem('bill_splitter_state');
        if (saved) {
            const parsed = JSON.parse(saved);
            state = Object.assign(state, parsed);
        }
    } catch (e) {
        console.warn('Could not load from localStorage:', e);
    }
}

// Glass Toast Notification
function showToast(message, type = 'info') {
    const toast = document.createElement('div');
    toast.className = `toast toast-${type}`;
    
    let icon = 'ℹ️';
    if (type === 'success') icon = '✓';
    if (type === 'error') icon = '⚠️';

    toast.innerHTML = `<span style="font-size:16px;">${icon}</span> <span>${message}</span>`;
    toastContainer.appendChild(toast);

    setTimeout(() => {
        if (toast.parentNode) {
            toast.parentNode.removeChild(toast);
        }
    }, 3200);
}

// Language System
function t(key) {
    const lang = state.settings.language || 'en';
    return (i18n[lang] && i18n[lang][key]) ? i18n[lang][key] : (i18n.en[key] || key);
}

function updateLanguageUI() {
    const lang = state.settings.language;
    const dict = i18n[lang];

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.textContent = dict[key];
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (dict[key]) el.placeholder = dict[key];
    });

    if (lang === 'en') {
        langFlag.textContent = '🇲🇾';
        langText.textContent = 'Tukar BM';
    } else {
        langFlag.textContent = '🇬🇧';
        langText.textContent = 'Switch EN';
    }

    applyTheme(state.settings.darkMode);
    renderPeopleUI();
    recalculateAndRender();
}

btnLang.addEventListener('click', () => {
    state.settings.language = state.settings.language === 'en' ? 'ms' : 'en';
    saveToStorage();
    updateLanguageUI();
});

// Theme System
function applyTheme(isDark) {
    if (isDark) {
        document.body.classList.add('dark-mode');
        themeIcon.textContent = '☀️';
        themeText.textContent = t('theme_light');
    } else {
        document.body.classList.remove('dark-mode');
        themeIcon.textContent = '🌙';
        themeText.textContent = t('theme_dark');
    }
}

btnTheme.addEventListener('click', () => {
    state.settings.darkMode = !state.settings.darkMode;
    applyTheme(state.settings.darkMode);
    saveToStorage();
});

// Extras (Tax, Service Fee, Discount) Accordion
btnToggleExtras.addEventListener('click', () => {
    extrasPanel.classList.toggle('open');
    extrasArrow.classList.toggle('rotated');
});

inputTax.addEventListener('input', () => {
    state.extras.taxPercent = Math.max(0, parseFloat(inputTax.value) || 0);
    saveToStorage();
    recalculateAndRender();
});

inputService.addEventListener('input', () => {
    state.extras.servicePercent = Math.max(0, parseFloat(inputService.value) || 0);
    saveToStorage();
    recalculateAndRender();
});

inputDiscount.addEventListener('input', () => {
    state.extras.discountAmount = Math.max(0, parseFloat(inputDiscount.value) || 0);
    saveToStorage();
    recalculateAndRender();
});

// Shopper Management
function addPerson() {
    const name = inputPerson.value.trim();
    if (!name) {
        showToast(t('toast_enter_name'), 'error');
        return;
    }

    const exists = state.people.some(p => p.name.toLowerCase() === name.toLowerCase());
    if (exists) {
        showToast(t('toast_name_exists'), 'error');
        return;
    }

    state.people.push({
        id: state.personIdCounter++,
        name: name,
        debt: 0,
        subtotal: 0
    });

    inputPerson.value = '';
    saveToStorage();
    renderPeopleUI();
    recalculateAndRender();
    showToast(t('toast_person_added'), 'success');
}

btnAddPerson.addEventListener('click', addPerson);
inputPerson.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        e.preventDefault();
        addPerson();
    }
});

function deletePerson(id) {
    const isSharing = state.items.some(item => item.sharedBy.includes(id));
    if (isSharing) {
        showToast(t('toast_person_in_use'), 'error');
        return;
    }

    state.people = state.people.filter(p => p.id !== id);
    saveToStorage();
    renderPeopleUI();
    recalculateAndRender();
    showToast(t('toast_person_removed'), 'info');
}

function renderPeopleUI() {
    peopleBadges.innerHTML = '';
    peopleCountEl.textContent = state.people.length;

    if (state.people.length === 0) {
        emptyPeopleHint.style.display = 'block';
    } else {
        emptyPeopleHint.style.display = 'none';
        state.people.forEach(p => {
            const badge = document.createElement('div');
            badge.className = 'badge';
            const firstLetter = p.name.charAt(0).toUpperCase();

            badge.innerHTML = `
                <span class="badge-avatar">${firstLetter}</span>
                <span>${p.name}</span>
                <span class="delete-badge" title="Remove">&times;</span>
            `;

            badge.querySelector('.delete-badge').addEventListener('click', (e) => {
                e.stopPropagation();
                deletePerson(p.id);
            });

            badge.addEventListener('click', () => {
                openPersonBreakdown(p.id);
            });

            peopleBadges.appendChild(badge);
        });
    }

    renderDynamicCheckboxes();
}

// Checkboxes for Sharing
function renderDynamicCheckboxes() {
    dynamicCheckboxes.innerHTML = '';

    if (state.people.length === 0) {
        dynamicCheckboxes.innerHTML = `<p class="empty-state">${t('empty_people')}</p>`;
        return;
    }

    state.people.forEach(p => {
        const label = document.createElement('label');
        label.innerHTML = `
            <input type="checkbox" class="cb-kongsi" value="${p.id}">
            <span>${p.name}</span>
        `;

        const cb = label.querySelector('input');
        cb.addEventListener('change', () => {
            if (cb.checked) {
                label.classList.add('checked');
            } else {
                label.classList.remove('checked');
            }
        });

        dynamicCheckboxes.appendChild(label);
    });
}

btnSelectAll.addEventListener('click', () => {
    document.querySelectorAll('.cb-kongsi').forEach(cb => {
        cb.checked = true;
        cb.closest('label').classList.add('checked');
    });
});

btnClearAll.addEventListener('click', () => {
    document.querySelectorAll('.cb-kongsi').forEach(cb => {
        cb.checked = false;
        cb.closest('label').classList.remove('checked');
    });
});

// Item Management
function addItem() {
    if (state.people.length === 0) {
        showToast(t('toast_need_people'), 'error');
        return;
    }

    const price = parseFloat(inputItemPrice.value);
    if (isNaN(price) || price <= 0) {
        showToast(t('toast_invalid_price'), 'error');
        inputItemPrice.focus();
        return;
    }

    const checkboxes = document.querySelectorAll('.cb-kongsi:checked');
    const selectedIds = Array.from(checkboxes).map(cb => parseInt(cb.value));

    if (selectedIds.length === 0) {
        showToast(t('toast_select_shopper'), 'error');
        return;
    }

    let name = inputItemName.value.trim();
    if (!name) {
        name = `${t('unnamed_item')} #${state.itemIdCounter}`;
    }

    state.items.push({
        id: state.itemIdCounter++,
        name: name,
        price: price,
        sharedBy: selectedIds
    });

    inputItemName.value = '';
    inputItemPrice.value = '';
    document.querySelectorAll('.cb-kongsi').forEach(cb => {
        cb.checked = false;
        cb.closest('label').classList.remove('checked');
    });

    qrContainer.style.display = 'none';
    saveToStorage();
    recalculateAndRender();
    showToast(t('toast_item_added'), 'success');
}

btnAddItem.addEventListener('click', addItem);
inputItemPrice.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        e.preventDefault();
        addItem();
    }
});

function deleteItem(id) {
    state.items = state.items.filter(i => i.id !== id);
    qrContainer.style.display = 'none';
    saveToStorage();
    recalculateAndRender();
    showToast(t('toast_item_deleted'), 'info');
}

// Fair Mathematical Splitting Engine
function recalculateAndRender() {
    let subtotal = 0;
    state.people.forEach(p => {
        p.subtotal = 0;
        p.debt = 0;
    });

    // 1. Calculate Base Item Shares
    state.items.forEach(item => {
        subtotal += item.price;
        const perPersonShare = item.price / item.sharedBy.length;
        item.sharedBy.forEach(pId => {
            const person = state.people.find(p => p.id === pId);
            if (person) {
                person.subtotal += perPersonShare;
            }
        });
    });

    // 2. Extra Fees & Discounts
    const taxRate = state.extras.taxPercent || 0;
    const serviceRate = state.extras.servicePercent || 0;
    const taxTotal = subtotal * (taxRate / 100);
    const serviceTotal = subtotal * (serviceRate / 100);

    const subtotalWithFees = subtotal + taxTotal + serviceTotal;
    const discountTotal = Math.min(state.extras.discountAmount || 0, subtotalWithFees);

    const grandTotal = Math.max(0, subtotalWithFees - discountTotal);
    const netExtraRatio = subtotal > 0 ? (grandTotal - subtotal) / subtotal : 0;

    // 3. Proportional Split of Extras to Each Person
    let runningRoundedSum = 0;
    let highestDebtPerson = null;
    let maxDebt = -1;

    state.people.forEach(p => {
        if (subtotal > 0 && p.subtotal > 0) {
            p.debt = p.subtotal + (p.subtotal * netExtraRatio);
        } else {
            p.debt = 0;
        }

        const rounded = Math.round(p.debt * 100) / 100;
        if (rounded > maxDebt) {
            maxDebt = rounded;
            highestDebtPerson = p;
        }
        runningRoundedSum += rounded;
    });

    // Handle single-cent rounding discrepancies
    const exactGrandTotalRounded = Math.round(grandTotal * 100) / 100;
    const diff = Math.round((exactGrandTotalRounded - runningRoundedSum) * 100) / 100;

    if (diff !== 0 && highestDebtPerson) {
        highestDebtPerson.debt += diff;
    }

    // 4. Render Updates
    renderReceiptItems();
    renderBuyersBreakdown();
    updateTotalsDisplay(subtotal, taxTotal, serviceTotal, discountTotal, grandTotal);
    renderDebtCards();
}

function renderReceiptItems() {
    itemList.innerHTML = '';
    const count = state.items.length;
    itemsCountEl.textContent = `${count} ${count === 1 ? t('item_count') : t('items_count')}`;

    if (count === 0) {
        emptyItemsState.style.display = 'flex';
        return;
    }

    emptyItemsState.style.display = 'none';

    state.items.forEach(item => {
        const li = document.createElement('li');
        const sharedNames = item.sharedBy
            .map(id => {
                const p = state.people.find(x => x.id === id);
                return p ? p.name : '';
            })
            .filter(Boolean)
            .join(', ');

        li.innerHTML = `
            <div class="item-info">
                <span class="item-name" title="${item.name}">${item.name}</span>
                <span class="item-meta">${t('shared_by')} <strong>${item.sharedBy.length}</strong> (${sharedNames})</span>
            </div>
            <div class="item-actions">
                <span class="item-price-tag">RM ${item.price.toFixed(2)}</span>
                <button type="button" class="delete-item-btn" title="Delete item">&times;</button>
            </div>
        `;

        li.querySelector('.delete-item-btn').addEventListener('click', () => {
            deleteItem(item.id);
        });

        itemList.appendChild(li);
    });
}

function updateTotalsDisplay(subtotal, tax, service, discount, grandTotal) {
    subTotalEl.textContent = `RM ${subtotal.toFixed(2)}`;
    grandTotalEl.textContent = `RM ${grandTotal.toFixed(2)}`;

    if (tax > 0) {
        rowTax.style.display = 'flex';
        taxAmountEl.textContent = `+RM ${tax.toFixed(2)}`;
    } else {
        rowTax.style.display = 'none';
    }

    if (service > 0) {
        rowService.style.display = 'flex';
        serviceAmountEl.textContent = `+RM ${service.toFixed(2)}`;
    } else {
        rowService.style.display = 'none';
    }

    if (discount > 0) {
        rowDiscount.style.display = 'flex';
        discountAmountEl.textContent = `-RM ${discount.toFixed(2)}`;
    } else {
        rowDiscount.style.display = 'none';
    }
}

function renderDebtCards() {
    debtCardsContainer.innerHTML = '';

    if (state.people.length === 0) {
        debtCardsContainer.innerHTML = `<p class="empty-state">${t('empty_people')}</p>`;
        return;
    }

    state.people.forEach(p => {
        const card = document.createElement('div');
        card.className = 'debt-card';

        // Count how many items this person shares
        const sharedItemsCount = state.items.filter(item => item.sharedBy.includes(p.id)).length;
        const firstLetter = p.name.charAt(0).toUpperCase();

        card.innerHTML = `
            <div class="debt-user">
                <div class="debt-avatar">${firstLetter}</div>
                <div>
                    <div class="debt-name">${p.name}</div>
                    <div class="debt-sub">${sharedItemsCount} ${sharedItemsCount === 1 ? t('item_count') : t('items_count')}</div>
                </div>
            </div>
            <div class="debt-amt">RM ${p.debt.toFixed(2)}</div>
        `;

        card.addEventListener('click', () => {
            openPersonBreakdown(p.id);
        });

        debtCardsContainer.appendChild(card);
    });
}

// What Each Buyer Bought Breakdown View
function renderBuyersBreakdown() {
    if (!buyersBreakdownList) return;
    buyersBreakdownList.innerHTML = '';

    if (state.people.length === 0 || state.items.length === 0) {
        if (emptyBuyersState) emptyBuyersState.style.display = 'flex';
        return;
    }

    if (emptyBuyersState) emptyBuyersState.style.display = 'none';

    state.people.forEach(person => {
        const card = document.createElement('div');
        card.className = 'buyer-card open';

        const personItems = state.items.filter(i => i.sharedBy.includes(person.id));
        const itemCount = personItems.length;
        const initial = person.name.charAt(0).toUpperCase();

        const extraShare = person.debt - person.subtotal;
        let extraShareHtml = '';
        if (Math.abs(extraShare) > 0.005) {
            const prefix = extraShare >= 0 ? '+RM ' : '-RM ';
            extraShareHtml = `
                <div class="buyer-item-row" style="color:var(--text-muted); font-size:12px;">
                    <span>${t('tax_fee_share')}</span>
                    <span>${prefix}${Math.abs(extraShare).toFixed(2)}</span>
                </div>
            `;
        }

        let itemsHtml = '';
        if (itemCount === 0) {
            itemsHtml = `<div class="empty-state">${t('no_items_bought')}</div>`;
        } else {
            itemsHtml = personItems.map(item => {
                const myShare = item.price / item.sharedBy.length;
                return `
                    <div class="buyer-item-row">
                        <div>
                            <div class="buyer-item-name">${item.name}</div>
                            <div class="buyer-item-split-hint">1/${item.sharedBy.length} ${t('shared_by')} (RM ${item.price.toFixed(2)})</div>
                        </div>
                        <div class="buyer-item-price">RM ${myShare.toFixed(2)}</div>
                    </div>
                `;
            }).join('');
        }

        card.innerHTML = `
            <div class="buyer-header">
                <div class="buyer-info">
                    <div class="buyer-avatar">${initial}</div>
                    <div class="buyer-name-group">
                        <span class="buyer-name">${person.name}</span>
                        <span class="buyer-item-count">${itemCount} ${itemCount === 1 ? t('item_count') : t('items_count')}</span>
                    </div>
                </div>
                <div class="buyer-right">
                    <span class="buyer-due">RM ${person.debt.toFixed(2)}</span>
                    <span class="buyer-chevron">▼</span>
                </div>
            </div>
            <div class="buyer-items-detail">
                ${itemsHtml}
                ${extraShareHtml}
                <div class="buyer-action-row">
                    <button type="button" class="buyer-mini-btn btn-copy-single">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
                        <span>${t('copy_buyer_bill')}</span>
                    </button>
                    <button type="button" class="buyer-mini-btn btn-wa-single">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 2c-5.508 0-9.986 4.477-9.986 9.984 0 1.76.459 3.481 1.332 5.003L2 22l5.176-1.357c1.469.801 3.125 1.225 4.855 1.225 5.508 0 9.986-4.477 9.986-9.984 0-5.507-4.478-9.984-9.986-9.984zm5.795 14.137c-.244.685-1.42 1.34-1.956 1.398-.519.057-1.196.082-1.93-.153-1.644-.526-3.84-2.28-4.992-3.877-1.258-1.745-1.408-2.617-1.408-3.327 0-.756.326-1.464.733-1.872.244-.244.53-.306.708-.306.177 0 .354.004.51.011.168.008.39-.063.61.465.228.547.781 1.905.85 2.045.068.14.114.306.023.491-.092.186-.138.303-.274.464-.137.162-.29.362-.414.485-.138.138-.282.288-.122.563.161.275.714 1.176 1.534 1.906 1.054.939 1.942 1.23 2.217 1.368.275.137.436.115.597-.07.161-.184.688-.801.871-1.077.184-.275.367-.23.611-.137.244.092 1.554.733 1.821.868.267.136.446.204.513.318.069.115.069.664-.175 1.349z"/></svg>
                        <span>${t('wa_buyer_bill')}</span>
                    </button>
                </div>
            </div>
        `;

        // Toggle card open/collapse
        const header = card.querySelector('.buyer-header');
        header.addEventListener('click', () => {
            card.classList.toggle('open');
        });

        // Copy single buyer bill
        const copyBtn = card.querySelector('.btn-copy-single');
        copyBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            copySingleBuyerBill(person);
        });

        // WhatsApp single buyer bill
        const waBtn = card.querySelector('.btn-wa-single');
        waBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            waSingleBuyerBill(person);
        });

        buyersBreakdownList.appendChild(card);
    });
}

function generateSingleBuyerText(person) {
    const personItems = state.items.filter(i => i.sharedBy.includes(person.id));
    if (personItems.length === 0) return null;

    let text = `👤 *${person.name}'s Bill*\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    personItems.forEach(item => {
        const share = item.price / item.sharedBy.length;
        text += `• ${item.name}: RM ${share.toFixed(2)} (1/${item.sharedBy.length})\n`;
    });
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `Subtotal: RM ${person.subtotal.toFixed(2)}\n`;

    const extraShare = person.debt - person.subtotal;
    if (Math.abs(extraShare) > 0.005) {
        text += `${t('tax_fee_share')} ${extraShare >= 0 ? '+RM ' : '-RM '}${Math.abs(extraShare).toFixed(2)}\n`;
    }
    text += `💰 *${t('modal_final')} RM ${person.debt.toFixed(2)}*\n\n`;
    text += `_${t('receipt_footer')}_`;
    return text;
}

function copySingleBuyerBill(person) {
    const text = generateSingleBuyerText(person);
    if (!text) {
        showToast(t('no_items_bought'), 'error');
        return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(() => {
            showToast(`${person.name}: ${t('buyer_bill_copied')}`, 'success');
        }).catch(() => {
            fallbackCopy(text);
        });
    } else {
        fallbackCopy(text);
    }
}

function waSingleBuyerBill(person) {
    const text = generateSingleBuyerText(person);
    if (!text) {
        showToast(t('no_items_bought'), 'error');
        return;
    }
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
}

// Person Detailed Itemized Breakdown Modal
function openPersonBreakdown(personId) {
    const person = state.people.find(p => p.id === personId);
    if (!person) return;

    modalPersonName.textContent = person.name;
    modalAvatar.textContent = person.name.charAt(0).toUpperCase();
    modalItemsList.innerHTML = '';

    const personItems = state.items.filter(i => i.sharedBy.includes(personId));

    if (personItems.length === 0) {
        modalItemsList.innerHTML = `<li style="color:var(--text-muted); justify-content:center;">${t('no_items_yet')}</li>`;
    } else {
        personItems.forEach(item => {
            const splitPrice = item.price / item.sharedBy.length;
            const li = document.createElement('li');
            li.innerHTML = `
                <div>
                    <strong>${item.name}</strong>
                    <div style="font-size:11px; color:var(--text-muted);">(1/${item.sharedBy.length} of RM ${item.price.toFixed(2)})</div>
                </div>
                <strong style="color:var(--accent-primary);">RM ${splitPrice.toFixed(2)}</strong>
            `;
            modalItemsList.appendChild(li);
        });
    }

    modalSubtotalVal.textContent = `RM ${person.subtotal.toFixed(2)}`;

    const extraShare = person.debt - person.subtotal;
    if (Math.abs(extraShare) > 0.005) {
        modalTaxLine.style.display = 'flex';
        modalExtraVal.textContent = (extraShare >= 0 ? '+RM ' : '-RM ') + Math.abs(extraShare).toFixed(2);
    } else {
        modalTaxLine.style.display = 'none';
    }

    modalFinalVal.textContent = `RM ${person.debt.toFixed(2)}`;
    modalBreakdown.style.display = 'flex';
}

function closeModal() {
    modalBreakdown.style.display = 'none';
}

btnCloseModal.addEventListener('click', closeModal);
btnDismissModal.addEventListener('click', closeModal);
modalBreakdown.addEventListener('click', (e) => {
    if (e.target === modalBreakdown) closeModal();
});
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && modalBreakdown.style.display === 'flex') {
        closeModal();
    }
});

// Receipt Formatting Engine for WhatsApp & Copy
function generateReceiptText() {
    if (state.items.length === 0) return null;

    let subtotal = 0;
    state.items.forEach(i => subtotal += i.price);

    const taxTotal = subtotal * (state.extras.taxPercent / 100);
    const serviceTotal = subtotal * (state.extras.servicePercent / 100);
    const discountTotal = Math.min(state.extras.discountAmount || 0, subtotal + taxTotal + serviceTotal);
    const grandTotal = Math.max(0, subtotal + taxTotal + serviceTotal - discountTotal);

    let text = `${t('receipt_header')}\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `${t('receipt_items_title')}\n`;

    state.items.forEach(item => {
        text += `• ${item.name}: RM ${item.price.toFixed(2)} (${item.sharedBy.length} ${t('pays')})\n`;
    });

    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `💵 ${t('subtotal')} RM ${subtotal.toFixed(2)}\n`;

    if (taxTotal > 0) {
        text += `📑 ${t('label_tax')} (${state.extras.taxPercent}%): +RM ${taxTotal.toFixed(2)}\n`;
    }
    if (serviceTotal > 0) {
        text += `🛎️ ${t('label_service')} (${state.extras.servicePercent}%): +RM ${serviceTotal.toFixed(2)}\n`;
    }
    if (discountTotal > 0) {
        text += `🏷️ ${t('label_discount')}: -RM ${discountTotal.toFixed(2)}\n`;
    }

    text += `💰 *${t('total_receipt')} RM ${grandTotal.toFixed(2)}*\n\n`;
    text += `${t('receipt_breakdown_title')}\n`;

    state.people.forEach(p => {
        if (p.debt > 0) {
            text += `👤 *${p.name}*: RM ${p.debt.toFixed(2)}\n`;
        }
    });

    text += `\n_${t('receipt_footer')}_`;
    return text;
}

// WhatsApp Share
btnWa.addEventListener('click', () => {
    const text = generateReceiptText();
    if (!text) {
        showToast(t('toast_no_items'), 'error');
        return;
    }
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
});

// Copy Text
btnCopy.addEventListener('click', () => {
    const text = generateReceiptText();
    if (!text) {
        showToast(t('toast_no_items'), 'error');
        return;
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(() => {
            showToast(t('toast_copied'), 'success');
        }).catch(() => {
            fallbackCopy(text);
        });
    } else {
        fallbackCopy(text);
    }
});

function fallbackCopy(text) {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.select();
    try {
        document.execCommand('copy');
        showToast(t('toast_copied'), 'success');
    } catch (e) {
        showToast('Copy failed, please copy manually.', 'error');
    }
    document.body.removeChild(textArea);
}

// QR Code Generator
btnQr.addEventListener('click', () => {
    const text = generateReceiptText();
    if (!text) {
        showToast(t('toast_no_items'), 'error');
        return;
    }

    const encoded = encodeURIComponent(text);
    qrImage.src = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encoded}&margin=10`;
    qrContainer.style.display = 'block';
    qrContainer.scrollIntoView({ behavior: 'smooth' });
});

btnCloseQr.addEventListener('click', () => {
    qrContainer.style.display = 'none';
});

// Reset All
btnReset.addEventListener('click', () => {
    if (confirm(t('toast_reset_confirm'))) {
        state.people = [];
        state.items = [];
        state.extras = { taxPercent: 0, servicePercent: 0, discountAmount: 0 };
        state.personIdCounter = 1;
        state.itemIdCounter = 1;

        inputTax.value = '0';
        inputService.value = '0';
        inputDiscount.value = '0';
        qrContainer.style.display = 'none';

        saveToStorage();
        renderPeopleUI();
        recalculateAndRender();
        showToast('All data has been reset.', 'info');
    }
});

// Tab Switching (By Items vs By Buyer)
if (tabBtnItems && tabBtnBuyers) {
    tabBtnItems.addEventListener('click', () => {
        tabBtnItems.classList.add('active');
        tabBtnBuyers.classList.remove('active');
        viewItems.style.display = 'block';
        viewBuyers.style.display = 'none';
    });

    tabBtnBuyers.addEventListener('click', () => {
        tabBtnBuyers.classList.add('active');
        tabBtnItems.classList.remove('active');
        viewBuyers.style.display = 'block';
        viewItems.style.display = 'none';
        renderBuyersBreakdown();
    });
}

// App Initialization
function initApp() {
    loadFromStorage();

    // Populate extra fee inputs if restored
    if (state.extras) {
        inputTax.value = state.extras.taxPercent || 0;
        inputService.value = state.extras.servicePercent || 0;
        inputDiscount.value = state.extras.discountAmount || 0;
    }

    applyTheme(state.settings.darkMode);
    updateLanguageUI();
    renderPeopleUI();
    recalculateAndRender();
}

initApp();