/**
 * Bill Splitter - Professional Clean Glass UI Logic, Settlement & Full-Stack Supabase Engine
 */

// Application State
let state = {
    people: [],
    items: [],
    extras: {
        taxPercent: 0,
        servicePercent: 0,
        discountAmount: 0
    },
    settings: {
        language: 'en',
        darkMode: true
    },
    personIdCounter: 1,
    itemIdCounter: 1
};

// Bilingual Dictionary
const i18n = {
    en: {
        title: "Bill Splitter",
        subtitle: "Smart group expense & grocery calculator",
        btn_reset: "Reset",
        theme_light: "Light",
        theme_dark: "Dark",
        step1: "Shoppers & Friends",
        step1_desc: "Add everyone splitting this bill",
        person_ph: "Enter name (e.g. Ali)",
        btn_add_person: "Add",
        no_people_yet: "No shoppers added yet. Enter names above.",
        step2: "Add Item / Expense",
        step2_desc: "Specify price and who shares it",
        item_ph: "Item name (e.g. Apples, Pizza)",
        price_ph: "0.00",
        share_label: "Who shares this item?",
        select_all: "Select All",
        clear_all: "Clear",
        empty_people: "Please add shoppers first.",
        btn_add_item: "Add to Bill",
        step3: "Bill & Breakdown",
        step3_desc: "Live itemized receipt & splits",
        no_items_yet: "Receipt is empty. Add items from the left panel.",
        tax_discount_title: "Tax, Service & Discount",
        label_tax: "SST / Tax (%)",
        label_service: "Service Fee (%)",
        label_discount: "Discount (RM)",
        subtotal: "Subtotal:",
        total_receipt: "Grand Total:",
        individual_splits: "Who Owes What",
        click_to_view_detail: "Click on any person to inspect itemized breakdown & settlement",
        step4: "Share & Export",
        step4_desc: "Send receipt to friends or copy breakdown",
        btn_wa: "WhatsApp",
        btn_copy: "Copy Text",
        btn_qr: "QR Code",
        btn_save_cloud: "Save Bill & Debts to Cloud",
        qr_desc: "Scan with camera to read complete receipt:",
        close: "Close",
        modal_subtotal: "Items Share:",
        modal_extra: "Tax & Fees Share:",
        modal_final: "Total to Pay:",
        items_count: "items",
        item_count: "item",
        pays: "pays",
        shared_by: "shared by",
        unnamed_item: "Item",
        toast_person_added: "Shopper added successfully!",
        toast_person_removed: "Shopper removed.",
        toast_person_in_use: "Cannot delete: This person is sharing items in the bill!",
        toast_enter_name: "Please enter a valid name.",
        toast_name_exists: "A shopper with this name already exists.",
        toast_item_added: "Item added to receipt!",
        toast_item_deleted: "Item removed.",
        toast_need_people: "Please add at least one person first.",
        toast_invalid_price: "Please enter a valid item price greater than 0.",
        toast_select_shopper: "Please select at least one person who shares this item.",
        toast_copied: "Receipt summary copied to clipboard!",
        toast_no_items: "Please add some items to your bill first!",
        toast_reset_confirm: "Are you sure you want to reset everything? All data will be cleared.",
        receipt_header: "🛒 *BILL SPLITTER RECEIPT*",
        receipt_items_title: "📋 *Items:*",
        receipt_breakdown_title: "👥 *Who Owes What:*",
        receipt_footer: "Generated by Bill Splitter",
        tab_by_items: "By Items",
        tab_by_buyers: "What Each Buyer Bought",
        empty_buyers_hint: "Add shoppers and items to see what each person bought.",
        copy_buyer_bill: "Copy Bill",
        wa_buyer_bill: "WhatsApp",
        no_items_bought: "Has not shared any items yet",
        buyer_bill_copied: "Bill copied!",
        tax_fee_share: "Tax & Fees:",
        step4_payment: "Who Paid The Cashier?",
        step4_payment_desc: "Record who paid upfront at the counter",
        paid_in_full: "Paid All",
        paid_total_label: "Total Paid:",
        settlement_title: "Settlement & Transfers",
        settlement_desc: "Direct transfers to balance all payments",
        settlement_no_payments: "Enter who paid in Step 4 to calculate transfers.",
        settlement_all_settled: "All settled! Nobody owes anyone anything.",
        needs_to_pay: "needs to pay",
        balance_gets_back: "Gets back",
        balance_owes: "Owes",
        balance_settled: "Settled",
        step5: "Share & Export",
        step5_desc: "Send receipt to friends or copy breakdown",
        toast_payment_updated: "Payment updated.",
        status_exact: "✅ Payments match grand total exactly",
        status_remaining: "⚠️ Remaining to match bill:",
        status_overpaid: "ℹ️ Overpaid cashier by:",
        receipt_payments_title: "💳 *Payments & Balances:*",
        receipt_settlement_title: "🔄 *Settlement Transfers:*",
        receipt_all_settled: "✅ All debts settled! No transfers needed.",
        
        // Detailed User Profile Modal
        profile_btn: "View",
        profile_title: "Member Profile",
        profile_sub: "Item Breakdown & Settlement Directives",
        profile_sec_a_title: "Purchase History & Share",
        profile_sec_b_title: "Settlement / Who to Pay",
        share_of: "share of",
        needs_to_pay_who: "Needs to pay",
        will_pay_you: "Will pay you",
        no_items_in_profile: "No items shared in this bill.",
        profile_all_settled: "All settled! No balance due.",
        upfront_paid: "Paid Upfront:",
        net_balance: "Net Balance:",

        // Supabase Auth & Cloud Dashboard
        auth_title: "Welcome to Bill Splitter",
        auth_subtitle: "Sign in or register to sync your debts & bills to Supabase cloud",
        auth_tab_login: "Sign In",
        auth_tab_signup: "Register",
        auth_name_label: "Your Display Name",
        auth_email_label: "Email Address",
        auth_pass_label: "Password",
        auth_btn_login: "Sign In",
        auth_btn_signup: "Create Account",
        auth_logout: "Log Out",
        auth_logged_out: "Logged out successfully.",
        auth_login_success: "Welcome back!",
        auth_signup_success: "Account created! You are now logged in.",
        auth_or: "or",
        auth_btn_guest: "Continue as Guest (Offline)",
        auth_guest_welcome: "Guest mode activated. Calculator available offline!",
        nav_calculator: "Split New Bill",
        nav_dashboard: "Cloud Debts & Balances",
        stat_i_owe: "My Total Outstanding Debt",
        stat_i_owe_sub: "Pending payments to others",
        stat_who_owes_me: "Who Owes Me",
        stat_owed_to_me_sub: "Pending money to collect",
        stat_net_balance: "Net Cloud Position",
        stat_net_sub: "Overall balance",
        dash_owed_to_me_title: "People Who Owe Me",
        dash_owed_to_me_desc: "Debts where you paid upfront and are awaiting reimbursement",
        dash_i_owe_title: "Debts I Owe to Others",
        dash_i_owe_desc: "Outstanding payments you need to settle",
        dash_bills_history: "Saved Bills History",
        dash_bills_history_desc: "Bills stored in your Supabase database",
        no_one_owes_you: "Nobody owes you money at the moment.",
        you_owe_nothing: "You don't owe anyone any money! 🎉",
        no_cloud_bills: "No bills saved to cloud yet.",
        mark_paid: "✓ Mark Paid",
        mark_pending: "↺ Mark Pending",
        status_paid: "Paid",
        status_pending: "Pending",
        toast_bill_saved_cloud: "Bill and settlements successfully saved to Supabase cloud!",
        toast_debt_marked_paid: "Debt marked as Paid!",
        toast_debt_marked_pending: "Debt marked as Pending.",
        toast_confirm_delete_bill: "Are you sure you want to delete this bill from the database?",
        toast_bill_deleted: "Bill deleted from database."
    },
    ms: {
        title: "Split Bil",
        subtitle: "Kiraan barang dapur & perbelanjaan kumpulan",
        btn_reset: "Padam Semua",
        theme_light: "Cerah",
        theme_dark: "Gelap",
        step1: "Senarai Rakan & Pembeli",
        step1_desc: "Tambah semua orang yang berkongsi bil ini",
        person_ph: "Masukkan nama (cth: Ali)",
        btn_add_person: "Tambah",
        no_people_yet: "Tiada pembeli lagi. Masukkan nama di atas.",
        step2: "Tambah Barang / Belanja",
        step2_desc: "Tetapkan harga dan siapa yang kongsi",
        item_ph: "Nama barang (cth: Epal, Pizza)",
        price_ph: "0.00",
        share_label: "Siapa kongsi barang ni?",
        select_all: "Pilih Semua",
        clear_all: "Kosongkan",
        empty_people: "Sila tambah nama orang dahulu.",
        btn_add_item: "Tambah Dalam Resit",
        step3: "Resit & Kiraan",
        step3_desc: "Rumusan bil & pecahan bayaran langsung",
        no_items_yet: "Resit kosong. Tambah barang dari panel sebelah.",
        tax_discount_title: "Cukai, Servis & Diskaun",
        label_tax: "SST / Cukai (%)",
        label_service: "Caj Servis (%)",
        label_discount: "Diskaun (RM)",
        subtotal: "Jumlah Kasar:",
        total_receipt: "Jumlah Keseluruhan:",
        individual_splits: "Bahagian Perlu Dibayar",
        click_to_view_detail: "Tekan mana-mana nama untuk lihat pecahan barang & bayaran balik",
        step4: "Kongsi & Eksport",
        step4_desc: "Hantar resit kepada rakan atau salin teks",
        btn_wa: "WhatsApp",
        btn_copy: "Salin Teks",
        btn_qr: "Kod QR",
        btn_save_cloud: "Simpan Bil & Hutang ke Cloud",
        qr_desc: "Imbas dengan kamera untuk baca resit penuh:",
        close: "Tutup",
        modal_subtotal: "Bahagian Barang:",
        modal_extra: "Bahagian Caj & Cukai:",
        modal_final: "Jumlah Bayaran:",
        items_count: "barang",
        item_count: "barang",
        pays: "perlu bayar",
        shared_by: "dikongsi",
        unnamed_item: "Barang",
        toast_person_added: "Nama berjaya ditambah!",
        toast_person_removed: "Nama berjaya dipadam.",
        toast_person_in_use: "Tak boleh padam! Nama ini ada dalam perkongsian barang di resit.",
        toast_enter_name: "Sila masukkan nama yang sah.",
        toast_name_exists: "Nama ini sudah ada dalam senarai.",
        toast_item_added: "Barang ditambah ke dalam resit!",
        toast_item_deleted: "Barang dipadam.",
        toast_need_people: "Sila tambah nama orang terlebih dahulu.",
        toast_invalid_price: "Sila masukkan harga yang sah melebihi 0.",
        toast_select_shopper: "Sila tandakan sekurang-kurangnya seorang yang berkongsi barang ini.",
        toast_copied: "Rumusan resit berjaya disalin ke papan klip!",
        toast_no_items: "Sila tambah barang dahulu!",
        toast_reset_confirm: "Adakah anda pasti mahu memadam semua data?",
        receipt_header: "🛒 *RESIT SPLIT BIL*",
        receipt_items_title: "📋 *Senarai Barang:*",
        receipt_breakdown_title: "👥 *Bahagian Perlu Dibayar:*",
        receipt_footer: "Dikira oleh Aplikasi Split Bil",
        tab_by_items: "Mengikut Barang",
        tab_by_buyers: "Apa Setiap Pembeli Beli",
        empty_buyers_hint: "Tambah pembeli dan barang untuk melihat pecahan setiap orang.",
        copy_buyer_bill: "Salin Bil",
        wa_buyer_bill: "WhatsApp",
        no_items_bought: "Belum berkongsi sebarang barang",
        buyer_bill_copied: "Bil berjaya disalin!",
        tax_fee_share: "Cukai & Caj:",
        step4_payment: "Siapa Bayar Di Kaunter?",
        step4_payment_desc: "Rekod siapa yang bayar dahulu semasa checkout",
        paid_in_full: "Bayar Semua",
        paid_total_label: "Jumlah Dibayar:",
        settlement_title: "Penyelesaian & Pindahan",
        settlement_desc: "Pindahan terus untuk selesaikan semua baki",
        settlement_no_payments: "Masukkan bayaran di Bahagian 4 untuk kira siapa bayar siapa.",
        settlement_all_settled: "Semua selesai! Tiada sesiapa berhutang lagi.",
        needs_to_pay: "perlu bayar kepada",
        balance_gets_back: "Dapat balik",
        balance_owes: "Perlu bayar",
        balance_settled: "Selesai",
        step5: "Kongsi & Eksport",
        step5_desc: "Hantar resit kepada rakan atau salin teks",
        toast_payment_updated: "Bayaran dikemaskini.",
        status_exact: "✅ Bayaran sama tepat dengan jumlah bil",
        status_remaining: "⚠️ Baki belum dibayar di kaunter:",
        status_overpaid: "ℹ️ Terlebih bayar di kaunter sebanyak:",
        receipt_payments_title: "💳 *Bayaran & Baki:*",
        receipt_settlement_title: "🔄 *Penyelesaian & Pindahan:*",
        receipt_all_settled: "✅ Semua hutang selesai! Tiada pindahan wang diperlukan.",

        // Detailed User Profile Modal
        profile_btn: "Lihat",
        profile_title: "Profil Ahli",
        profile_sub: "Pecahan Barang & Arahan Pembayaran",
        profile_sec_a_title: "Rekod Pembelian & Bahagian",
        profile_sec_b_title: "Penyelesaian / Siapa Perlu Dibayar",
        share_of: "bahagian daripada",
        needs_to_pay_who: "Perlu bayar kepada",
        will_pay_you: "Akan bayar kepada anda",
        no_items_in_profile: "Tiada barang dikongsi dalam bil ini.",
        profile_all_settled: "Semua selesai! Tiada baki tertunggak.",
        upfront_paid: "Dibayar Dahulu:",
        net_balance: "Baki Bersih:",

        // Supabase Auth & Cloud Dashboard
        auth_title: "Selamat Datang ke Split Bil",
        auth_subtitle: "Log masuk atau daftar akaun untuk sync hutang & resit ke database Supabase",
        auth_tab_login: "Log Masuk",
        auth_tab_signup: "Daftar Akaun",
        auth_name_label: "Nama Paparan Anda",
        auth_email_label: "Alamat Emel",
        auth_pass_label: "Kata Laluan",
        auth_btn_login: "Log Masuk",
        auth_btn_signup: "Cipta Akaun",
        auth_logout: "Log Keluar",
        auth_logged_out: "Berjaya log keluar.",
        auth_login_success: "Selamat kembali!",
        auth_signup_success: "Akaun berjaya dicipta! Anda kini telah log masuk.",
        auth_or: "atau",
        auth_btn_guest: "Teruskan Sebagai Tetamu (Offline)",
        auth_guest_welcome: "Mod tetamu aktif. Kalkulator sedia digunakan secara offline!",
        nav_calculator: "Kira Bil Baru",
        nav_dashboard: "Hutang & Baki Cloud",
        stat_i_owe: "Jumlah Hutang Perlu Saya Bayar",
        stat_i_owe_sub: "Bayaran tertunggak kepada rakan",
        stat_who_owes_me: "Siapa Berhutang Dengan Saya",
        stat_owed_to_me_sub: "Duit yang perlu dikutip",
        stat_net_balance: "Kedudukan Bersih Cloud",
        stat_net_sub: "Baki keseluruhan",
        dash_owed_to_me_title: "Rakan Yang Berhutang Dengan Saya",
        dash_owed_to_me_desc: "Hutang di mana anda dahulukan duit dan menunggu bayaran balik",
        dash_i_owe_title: "Hutang Perlu Saya Bayar Kepada Orang Lain",
        dash_i_owe_desc: "Bayaran tertunggak yang perlu anda selesaikan",
        dash_bills_history: "Sejarah Bil Tersimpan",
        dash_bills_history_desc: "Bil yang disimpan dalam database Supabase",
        no_one_owes_you: "Tiada sesiapa berhutang dengan anda buat masa ini.",
        you_owe_nothing: "Anda tidak berhutang dengan sesiapa! 🎉",
        no_cloud_bills: "Tiada bil disimpan di cloud lagi.",
        mark_paid: "✓ Tanda Selesai",
        mark_pending: "↺ Tanda Belum Selesai",
        status_paid: "Selesai",
        status_pending: "Belum Selesai",
        toast_bill_saved_cloud: "Bil dan rekod hutang berjaya disimpan ke cloud Supabase!",
        toast_debt_marked_paid: "Hutang ditandakan sebagai Selesai!",
        toast_debt_marked_pending: "Hutang ditandakan sebagai Belum Selesai.",
        toast_confirm_delete_bill: "Adakah anda pasti mahu memadam bil ini dari database?",
        toast_bill_deleted: "Bil dipadam dari database."
    }
};

// -------------------------------------------------------------
// SUPABASE CLIENT INITIALIZATION
// -------------------------------------------------------------
const SUPABASE_URL = 'https://tdmgvqxncfezswudufyp.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbWd2cXhuY2ZlenN3dWR1ZnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0MzAxNzgsImV4cCI6MjEwNjAwNjE3OH0.9bXEaeIXxL2TkTlbi_mB8LIgtlzFQNI5-SkRtJgDV2I';

let supabaseClient = null;
if (window.supabase && typeof window.supabase.createClient === 'function') {
    supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
}

let currentUser = null;
let isGuestMode = false;
let authMode = 'login'; // 'login' or 'signup'
let cloudDebts = [];
let cloudBills = [];
let currentAppTab = 'calculator';

// -------------------------------------------------------------
// DOM ELEMENTS
// -------------------------------------------------------------
// Top Header & User Pill
const appTitle = document.getElementById('app-title');
const appSubtitle = document.getElementById('app-subtitle');
const userHeaderProfile = document.getElementById('user-header-profile');
const headerUserPill = document.getElementById('header-user-pill');
const headerUserAvatar = document.getElementById('header-user-avatar');
const headerUserName = document.getElementById('header-user-name');
const headerUserEmail = document.getElementById('header-user-email');
const btnLogout = document.getElementById('btn-logout');
const btnHeaderLogin = document.getElementById('btn-header-login');
const btnReset = document.getElementById('btn-reset');
const btnLang = document.getElementById('btn-lang');
const langFlag = document.getElementById('lang-flag');
const langText = document.getElementById('lang-text');
const btnTheme = document.getElementById('btn-theme');
const themeIcon = document.getElementById('theme-icon');
const themeText = document.getElementById('theme-text');

// Authentication Screen
const authScreen = document.getElementById('auth-screen');
const authTitle = document.getElementById('auth-title');
const authSubtitle = document.getElementById('auth-subtitle');
const tabLogin = document.getElementById('tab-login');
const tabSignup = document.getElementById('tab-signup');
const authAlert = document.getElementById('auth-alert');
const authForm = document.getElementById('auth-form');
const fieldDisplayName = document.getElementById('field-display-name');
const inputDisplayName = document.getElementById('input-display-name');
const inputAuthEmail = document.getElementById('input-auth-email');
const inputAuthPassword = document.getElementById('input-auth-password');
const btnAuthSubmit = document.getElementById('btn-auth-submit');
const authBtnText = document.getElementById('auth-btn-text');
const btnGuestMode = document.getElementById('btn-guest-mode');

// Main Authenticated / Active App Wrapper & Nav
const mainAppContent = document.getElementById('main-app-content');
const navBtnCalculator = document.getElementById('nav-btn-calculator');
const navBtnDashboard = document.getElementById('nav-btn-dashboard');
const navDebtCount = document.getElementById('nav-debt-count');
const viewCalculator = document.getElementById('view-calculator');
const viewDashboard = document.getElementById('view-dashboard');

// Step 1: People
const inputPerson = document.getElementById('input-person');
const btnAddPerson = document.getElementById('btn-add-person');
const peopleBadges = document.getElementById('people-badges');
const emptyPeopleHint = document.getElementById('empty-people-hint');
const peopleCountEl = document.getElementById('people-count');

// Step 2: Items
const inputItemName = document.getElementById('item-name');
const inputItemPrice = document.getElementById('item-price');
const btnAddItem = document.getElementById('btn-add-item');
const dynamicCheckboxes = document.getElementById('dynamic-checkboxes');
const btnSelectAll = document.getElementById('btn-select-all');
const btnClearAll = document.getElementById('btn-clear-all');

// Step 3: Breakdown & Receipt
const itemList = document.getElementById('item-list');
const emptyItemsState = document.getElementById('empty-items-state');
const itemsCountEl = document.getElementById('items-count');

// Buyer breakdown & Tab elements
const tabBtnItems = document.getElementById('tab-btn-items');
const tabBtnBuyers = document.getElementById('tab-btn-buyers');
const viewItems = document.getElementById('view-items');
const viewBuyers = document.getElementById('view-buyers');
const buyersBreakdownList = document.getElementById('buyers-breakdown-list');
const emptyBuyersState = document.getElementById('empty-buyers-state');

// Cashier payments & Settlement elements (Step 4)
const payerInputsContainer = document.getElementById('payer-inputs-container');
const paidTotalPill = document.getElementById('paid-total-pill');
const paymentStatusBar = document.getElementById('payment-status-bar');
const settlementContainer = document.getElementById('settlement-container');
const settlementCountPill = document.getElementById('settlement-count-pill');

// Extras Accordion
const btnToggleExtras = document.getElementById('btn-toggle-extras');
const extrasPanel = document.getElementById('extras-panel');
const extrasArrow = document.getElementById('extras-arrow');
const inputTax = document.getElementById('input-tax');
const inputService = document.getElementById('input-service');
const inputDiscount = document.getElementById('input-discount');

// Summary Totals
const subTotalEl = document.getElementById('sub-total');
const grandTotalEl = document.getElementById('grand-total');
const rowTax = document.getElementById('row-tax');
const taxAmountEl = document.getElementById('tax-amount');
const rowService = document.getElementById('row-service');
const serviceAmountEl = document.getElementById('service-amount');
const rowDiscount = document.getElementById('row-discount');
const discountAmountEl = document.getElementById('discount-amount');
const debtCardsContainer = document.getElementById('debt-cards-container');

// Step 5: Export & Cloud Save
const btnWa = document.getElementById('btn-whatsapp');
const btnCopy = document.getElementById('btn-copy');
const btnQr = document.getElementById('btn-generate-qr');
const btnSaveCloud = document.getElementById('btn-save-cloud');
const qrContainer = document.getElementById('qr-container');
const qrImage = document.getElementById('qr-image');
const btnCloseQr = document.getElementById('btn-close-qr');

// Cloud Dashboard elements
const statTotalIOwe = document.getElementById('stat-total-i-owe');
const statTotalOwedToMe = document.getElementById('stat-total-owed-to-me');
const statNetPosition = document.getElementById('stat-net-position');
const statNetSub = document.getElementById('stat-net-sub');
const btnRefreshDebts = document.getElementById('btn-refresh-debts');
const listWhoOwesMe = document.getElementById('list-who-owes-me');
const listIOwe = document.getElementById('list-i-owe');
const listCloudBills = document.getElementById('list-cloud-bills');
const cloudBillsCount = document.getElementById('cloud-bills-count');

// Detailed User Profile Modal Elements
const profileModal = document.getElementById('profile-modal');
const profileAvatar = document.getElementById('profile-avatar');
const profileName = document.getElementById('profile-name');
const profileSub = document.getElementById('profile-sub');
const btnCloseProfileModal = document.getElementById('btn-close-profile-modal');
const btnDismissProfileModal = document.getElementById('btn-dismiss-profile-modal');
const profileItemsList = document.getElementById('profile-items-list');
const profileSubtotalVal = document.getElementById('profile-subtotal-val');
const profileTaxLine = document.getElementById('profile-tax-line');
const profileExtraVal = document.getElementById('profile-extra-val');
const profileFinalVal = document.getElementById('profile-final-val');
const profilePaidVal = document.getElementById('profile-paid-val');
const profileBalanceVal = document.getElementById('profile-balance-val');
const profileSettlementList = document.getElementById('profile-settlement-list');
const btnProfileWa = document.getElementById('btn-profile-wa');
const btnProfileCopy = document.getElementById('btn-profile-copy');
let activeProfilePersonId = null;

// Legacy Breakdown Modal Elements (Fallbacks)
const modalBreakdown = document.getElementById('modal-breakdown');
const modalPersonName = document.getElementById('modal-person-name');
const modalAvatar = document.getElementById('modal-avatar');
const modalItemsList = document.getElementById('modal-items-list');
const modalSubtotalVal = document.getElementById('modal-subtotal-val');
const modalTaxLine = document.getElementById('modal-tax-line');
const modalExtraVal = document.getElementById('modal-extra-val');
const modalFinalVal = document.getElementById('modal-final-val');
const btnCloseModal = document.getElementById('btn-close-modal');
const btnDismissModal = document.getElementById('btn-dismiss-modal');

// Toast Container
const toastContainer = document.getElementById('toast-container');

// -------------------------------------------------------------
// LOCAL STORAGE MANAGEMENT
// -------------------------------------------------------------
function saveToStorage() {
    try {
        localStorage.setItem('bill_splitter_state', JSON.stringify(state));
    } catch (e) {
        console.warn('LocalStorage error:', e);
    }
}

function loadFromStorage() {
    try {
        const saved = localStorage.getItem('bill_splitter_state');
        if (saved) {
            const parsed = JSON.parse(saved);
            state = Object.assign(state, parsed);
            if (state.people && Array.isArray(state.people)) {
                state.people.forEach(p => {
                    if (typeof p.amountPaid !== 'number' || isNaN(p.amountPaid)) {
                        p.amountPaid = 0;
                    }
                    if (typeof p.balance !== 'number' || isNaN(p.balance)) {
                        p.balance = 0;
                    }
                });
            }
        }
    } catch (e) {
        console.warn('Could not load from localStorage:', e);
    }
}

// -------------------------------------------------------------
// GLASS TOAST NOTIFICATION
// -------------------------------------------------------------
function showToast(message, type = 'info') {
    if (!toastContainer) return;
    const toast = document.createElement('div');
    toast.className = `toast toast-${type}`;
    
    let icon = 'ℹ️';
    if (type === 'success') icon = '✓';
    if (type === 'error') icon = '⚠️';

    toast.innerHTML = `<span style="font-size:16px;">${icon}</span> <span>${message}</span>`;
    toastContainer.appendChild(toast);

    setTimeout(() => {
        if (toast.parentNode) {
            toast.parentNode.removeChild(toast);
        }
    }, 3200);
}

// -------------------------------------------------------------
// LANGUAGE & THEME SYSTEM
// -------------------------------------------------------------
function t(key) {
    const lang = state.settings.language || 'en';
    return (i18n[lang] && i18n[lang][key]) ? i18n[lang][key] : (i18n.en[key] || key);
}

function updateLanguageUI() {
    const lang = state.settings.language;
    const dict = i18n[lang] || i18n.en;

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) el.textContent = dict[key];
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (dict[key]) el.placeholder = dict[key];
    });

    if (lang === 'en') {
        if (langFlag) langFlag.textContent = '🇲🇾';
        if (langText) langText.textContent = 'Tukar BM';
    } else {
        if (langFlag) langFlag.textContent = '🇬🇧';
        if (langText) langText.textContent = 'Switch EN';
    }

    applyTheme(state.settings.darkMode);
    renderPeopleUI();
    recalculateAndRender();
    if (currentUser) {
        renderCloudDashboard();
    }
}

if (btnLang) {
    btnLang.addEventListener('click', () => {
        state.settings.language = state.settings.language === 'en' ? 'ms' : 'en';
        saveToStorage();
        updateLanguageUI();
    });
}

function applyTheme(isDark) {
    if (isDark) {
        document.body.classList.add('dark-mode');
        if (themeIcon) themeIcon.textContent = '☀️';
        if (themeText) themeText.textContent = t('theme_light');
    } else {
        document.body.classList.remove('dark-mode');
        if (themeIcon) themeIcon.textContent = '🌙';
        if (themeText) themeText.textContent = t('theme_dark');
    }
}

if (btnTheme) {
    btnTheme.addEventListener('click', () => {
        state.settings.darkMode = !state.settings.darkMode;
        applyTheme(state.settings.darkMode);
        saveToStorage();
    });
}

// -------------------------------------------------------------
// EXTRAS (TAX, SERVICE FEE, DISCOUNT) ACCORDION
// -------------------------------------------------------------
if (btnToggleExtras) {
    btnToggleExtras.addEventListener('click', () => {
        extrasPanel.classList.toggle('open');
        extrasArrow.classList.toggle('rotated');
    });
}

if (inputTax) {
    inputTax.addEventListener('input', () => {
        state.extras.taxPercent = Math.max(0, parseFloat(inputTax.value) || 0);
        saveToStorage();
        recalculateAndRender();
    });
}

if (inputService) {
    inputService.addEventListener('input', () => {
        state.extras.servicePercent = Math.max(0, parseFloat(inputService.value) || 0);
        saveToStorage();
        recalculateAndRender();
    });
}

if (inputDiscount) {
    inputDiscount.addEventListener('input', () => {
        state.extras.discountAmount = Math.max(0, parseFloat(inputDiscount.value) || 0);
        saveToStorage();
        recalculateAndRender();
    });
}

// -------------------------------------------------------------
// SHOPPER MANAGEMENT (STEP 1)
// -------------------------------------------------------------
function addPerson() {
    const name = inputPerson.value.trim();
    if (!name) {
        showToast(t('toast_enter_name'), 'error');
        return;
    }

    const exists = state.people.some(p => p.name.toLowerCase() === name.toLowerCase());
    if (exists) {
        showToast(t('toast_name_exists'), 'error');
        return;
    }

    state.people.push({
        id: state.personIdCounter++,
        name: name,
        debt: 0,
        subtotal: 0,
        amountPaid: 0,
        balance: 0
    });

    inputPerson.value = '';
    saveToStorage();
    renderPeopleUI();
    recalculateAndRender();
    showToast(t('toast_person_added'), 'success');
}

if (btnAddPerson) btnAddPerson.addEventListener('click', addPerson);
if (inputPerson) {
    inputPerson.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            addPerson();
        }
    });
}

function deletePerson(id) {
    const isSharing = state.items.some(item => item.sharedBy.includes(id));
    if (isSharing) {
        showToast(t('toast_person_in_use'), 'error');
        return;
    }

    state.people = state.people.filter(p => p.id !== id);
    saveToStorage();
    renderPeopleUI();
    recalculateAndRender();
    showToast(t('toast_person_removed'), 'info');
}

function renderPeopleUI() {
    if (!peopleBadges) return;
    peopleBadges.innerHTML = '';
    if (peopleCountEl) peopleCountEl.textContent = state.people.length;

    if (state.people.length === 0) {
        if (emptyPeopleHint) emptyPeopleHint.style.display = 'block';
    } else {
        if (emptyPeopleHint) emptyPeopleHint.style.display = 'none';
        state.people.forEach(p => {
            const badge = document.createElement('div');
            badge.className = 'badge';
            const firstLetter = p.name.charAt(0).toUpperCase();

            badge.innerHTML = `
                <span class="badge-avatar">${firstLetter}</span>
                <span class="badge-name">${p.name}</span>
                <button type="button" class="badge-view-btn" title="${t('profile_btn')} ${p.name}">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                </button>
                <span class="delete-badge" title="Remove">&times;</span>
            `;

            // Profile view button
            const viewBtn = badge.querySelector('.badge-view-btn');
            if (viewBtn) {
                viewBtn.addEventListener('click', (e) => {
                    e.stopPropagation();
                    openProfileModal(p.id);
                });
            }

            // Remove button
            badge.querySelector('.delete-badge').addEventListener('click', (e) => {
                e.stopPropagation();
                deletePerson(p.id);
            });

            // Clicking the badge also opens detailed profile
            badge.addEventListener('click', () => {
                openProfileModal(p.id);
            });

            peopleBadges.appendChild(badge);
        });
    }

    renderDynamicCheckboxes();
}

// -------------------------------------------------------------
// CHECKBOXES FOR SHARING (STEP 2)
// -------------------------------------------------------------
function renderDynamicCheckboxes() {
    if (!dynamicCheckboxes) return;
    dynamicCheckboxes.innerHTML = '';

    if (state.people.length === 0) {
        dynamicCheckboxes.innerHTML = `<p class="empty-state">${t('empty_people')}</p>`;
        return;
    }

    state.people.forEach(p => {
        const label = document.createElement('label');
        label.innerHTML = `
            <input type="checkbox" class="cb-kongsi" value="${p.id}">
            <span>${p.name}</span>
        `;

        const cb = label.querySelector('input');
        cb.addEventListener('change', () => {
            if (cb.checked) {
                label.classList.add('checked');
            } else {
                label.classList.remove('checked');
            }
        });

        dynamicCheckboxes.appendChild(label);
    });
}

if (btnSelectAll) {
    btnSelectAll.addEventListener('click', () => {
        document.querySelectorAll('.cb-kongsi').forEach(cb => {
            cb.checked = true;
            cb.closest('label').classList.add('checked');
        });
    });
}

if (btnClearAll) {
    btnClearAll.addEventListener('click', () => {
        document.querySelectorAll('.cb-kongsi').forEach(cb => {
            cb.checked = false;
            cb.closest('label').classList.remove('checked');
        });
    });
}

// -------------------------------------------------------------
// ITEM MANAGEMENT (STEP 2)
// -------------------------------------------------------------
function addItem() {
    if (state.people.length === 0) {
        showToast(t('toast_need_people'), 'error');
        return;
    }

    const price = parseFloat(inputItemPrice.value);
    if (isNaN(price) || price <= 0) {
        showToast(t('toast_invalid_price'), 'error');
        inputItemPrice.focus();
        return;
    }

    const checkboxes = document.querySelectorAll('.cb-kongsi:checked');
    const selectedIds = Array.from(checkboxes).map(cb => parseInt(cb.value));

    if (selectedIds.length === 0) {
        showToast(t('toast_select_shopper'), 'error');
        return;
    }

    let name = inputItemName.value.trim();
    if (!name) {
        name = `${t('unnamed_item')} #${state.itemIdCounter}`;
    }

    state.items.push({
        id: state.itemIdCounter++,
        name: name,
        price: price,
        sharedBy: selectedIds
    });

    inputItemName.value = '';
    inputItemPrice.value = '';
    document.querySelectorAll('.cb-kongsi').forEach(cb => {
        cb.checked = false;
        cb.closest('label').classList.remove('checked');
    });

    if (qrContainer) qrContainer.style.display = 'none';
    saveToStorage();
    recalculateAndRender();
    showToast(t('toast_item_added'), 'success');
}

if (btnAddItem) btnAddItem.addEventListener('click', addItem);
if (inputItemPrice) {
    inputItemPrice.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            e.preventDefault();
            addItem();
        }
    });
}

function deleteItem(id) {
    state.items = state.items.filter(i => i.id !== id);
    if (qrContainer) qrContainer.style.display = 'none';
    saveToStorage();
    recalculateAndRender();
    showToast(t('toast_item_deleted'), 'info');
}

// -------------------------------------------------------------
// FAIR MATHEMATICAL SPLITTING ENGINE
// -------------------------------------------------------------
function recalculateAndRender() {
    let subtotal = 0;
    state.people.forEach(p => {
        p.subtotal = 0;
        p.debt = 0;
    });

    // 1. Calculate Base Item Shares
    state.items.forEach(item => {
        subtotal += item.price;
        const perPersonShare = item.price / item.sharedBy.length;
        item.sharedBy.forEach(pId => {
            const person = state.people.find(p => p.id === pId);
            if (person) {
                person.subtotal += perPersonShare;
            }
        });
    });

    // 2. Extra Fees & Discounts
    const taxRate = state.extras.taxPercent || 0;
    const serviceRate = state.extras.servicePercent || 0;
    const taxTotal = subtotal * (taxRate / 100);
    const serviceTotal = subtotal * (serviceRate / 100);

    const subtotalWithFees = subtotal + taxTotal + serviceTotal;
    const discountTotal = Math.min(state.extras.discountAmount || 0, subtotalWithFees);

    const grandTotal = Math.max(0, subtotalWithFees - discountTotal);
    const netExtraRatio = subtotal > 0 ? (grandTotal - subtotal) / subtotal : 0;

    // 3. Proportional Split of Extras to Each Person
    let runningRoundedSum = 0;
    let highestDebtPerson = null;
    let maxDebt = -1;

    state.people.forEach(p => {
        if (subtotal > 0 && p.subtotal > 0) {
            p.debt = p.subtotal + (p.subtotal * netExtraRatio);
        } else {
            p.debt = 0;
        }

        const rounded = Math.round(p.debt * 100) / 100;
        if (rounded > maxDebt) {
            maxDebt = rounded;
            highestDebtPerson = p;
        }
        runningRoundedSum += rounded;
    });

    // Handle single-cent rounding discrepancies
    const exactGrandTotalRounded = Math.round(grandTotal * 100) / 100;
    const diff = Math.round((exactGrandTotalRounded - runningRoundedSum) * 100) / 100;

    if (diff !== 0 && highestDebtPerson) {
        highestDebtPerson.debt += diff;
    }

    // 3.5 Settlement & Balances Calculation
    const transactions = calculateSettlements(grandTotal);

    // 4. Render Updates
    renderReceiptItems();
    renderBuyersBreakdown();
    updateTotalsDisplay(subtotal, taxTotal, serviceTotal, discountTotal, grandTotal);
    renderDebtCards();
    renderPayerInputs(grandTotal);
    renderSettlementUI(transactions, grandTotal);
}

function renderReceiptItems() {
    if (!itemList) return;
    itemList.innerHTML = '';
    const count = state.items.length;
    if (itemsCountEl) itemsCountEl.textContent = `${count} ${count === 1 ? t('item_count') : t('items_count')}`;

    if (count === 0) {
        if (emptyItemsState) emptyItemsState.style.display = 'flex';
        return;
    }

    if (emptyItemsState) emptyItemsState.style.display = 'none';

    state.items.forEach(item => {
        const li = document.createElement('li');
        const sharedNames = item.sharedBy
            .map(id => {
                const p = state.people.find(x => x.id === id);
                return p ? p.name : '';
            })
            .filter(Boolean)
            .join(', ');

        li.innerHTML = `
            <div class="item-info">
                <span class="item-name" title="${item.name}">${item.name}</span>
                <span class="item-meta">${t('shared_by')} <strong>${item.sharedBy.length}</strong> (${sharedNames})</span>
            </div>
            <div class="item-actions">
                <span class="item-price-tag">RM ${item.price.toFixed(2)}</span>
                <button type="button" class="delete-item-btn" title="Delete item">&times;</button>
            </div>
        `;

        li.querySelector('.delete-item-btn').addEventListener('click', () => {
            deleteItem(item.id);
        });

        itemList.appendChild(li);
    });
}

function updateTotalsDisplay(subtotal, tax, service, discount, grandTotal) {
    if (subTotalEl) subTotalEl.textContent = `RM ${subtotal.toFixed(2)}`;
    if (grandTotalEl) grandTotalEl.textContent = `RM ${grandTotal.toFixed(2)}`;

    if (rowTax && taxAmountEl) {
        if (tax > 0) {
            rowTax.style.display = 'flex';
            taxAmountEl.textContent = `+RM ${tax.toFixed(2)}`;
        } else {
            rowTax.style.display = 'none';
        }
    }

    if (rowService && serviceAmountEl) {
        if (service > 0) {
            rowService.style.display = 'flex';
            serviceAmountEl.textContent = `+RM ${service.toFixed(2)}`;
        } else {
            rowService.style.display = 'none';
        }
    }

    if (rowDiscount && discountAmountEl) {
        if (discount > 0) {
            rowDiscount.style.display = 'flex';
            discountAmountEl.textContent = `-RM ${discount.toFixed(2)}`;
        } else {
            rowDiscount.style.display = 'none';
        }
    }
}

function renderDebtCards() {
    if (!debtCardsContainer) return;
    debtCardsContainer.innerHTML = '';

    if (state.people.length === 0) {
        debtCardsContainer.innerHTML = `<p class="empty-state">${t('empty_people')}</p>`;
        return;
    }

    state.people.forEach(p => {
        const card = document.createElement('div');
        card.className = 'debt-card';

        const sharedItemsCount = state.items.filter(item => item.sharedBy.includes(p.id)).length;
        const firstLetter = p.name.charAt(0).toUpperCase();

        let paidBadge = '';
        if (typeof p.amountPaid === 'number' && p.amountPaid > 0) {
            const bal = p.balance || 0;
            const balClass = bal >= 0 ? 'color:var(--color-success);' : 'color:var(--color-danger);';
            const balSign = bal >= 0 ? '+' : '-';
            paidBadge = `<div style="font-size:11px; ${balClass} font-weight:700;">Paid: RM ${p.amountPaid.toFixed(2)} (${balSign}RM ${Math.abs(bal).toFixed(2)})</div>`;
        }

        card.innerHTML = `
            <div class="debt-user">
                <div class="debt-avatar">${firstLetter}</div>
                <div>
                    <div class="debt-name">${p.name}</div>
                    <div class="debt-sub">${sharedItemsCount} ${sharedItemsCount === 1 ? t('item_count') : t('items_count')}</div>
                    ${paidBadge}
                </div>
            </div>
            <div class="debt-right-col" style="display:flex; align-items:center; gap:8px;">
                <div class="debt-amt">RM ${p.debt.toFixed(2)}</div>
                <button type="button" class="debt-view-btn mini-btn glass-btn" title="${t('profile_btn')} ${p.name}">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                </button>
            </div>
        `;

        card.addEventListener('click', () => {
            openProfileModal(p.id);
        });

        debtCardsContainer.appendChild(card);
    });
}

// -------------------------------------------------------------
// SETTLEMENT & CASHIER PAYMENTS LOGIC (STEP 4)
// -------------------------------------------------------------
function calculateSettlements(grandTotal) {
    // 1. Calculate balance for each person: balance = amountPaid - debt
    state.people.forEach(p => {
        const paid = (typeof p.amountPaid === 'number' && !isNaN(p.amountPaid)) ? p.amountPaid : 0;
        p.amountPaid = paid;
        p.balance = Math.round((paid - p.debt) * 100) / 100;
    });

    // 2. Separate into debtors and creditors
    const debtors = [];
    const creditors = [];

    state.people.forEach(p => {
        if (p.balance < -0.005) {
            debtors.push({ id: p.id, name: p.name, amount: Math.round(-p.balance * 100) / 100 });
        } else if (p.balance > 0.005) {
            creditors.push({ id: p.id, name: p.name, amount: Math.round(p.balance * 100) / 100 });
        }
    });

    // 3. Sort descending for greedy optimal matches
    debtors.sort((a, b) => b.amount - a.amount);
    creditors.sort((a, b) => b.amount - a.amount);

    const transactions = [];
    let dIdx = 0;
    let cIdx = 0;

    while (dIdx < debtors.length && cIdx < creditors.length) {
        const debtor = debtors[dIdx];
        const creditor = creditors[cIdx];
        const transfer = Math.round(Math.min(debtor.amount, creditor.amount) * 100) / 100;

        if (transfer > 0.005) {
            transactions.push({
                fromId: debtor.id,
                from: debtor.name,
                toId: creditor.id,
                to: creditor.name,
                amount: transfer
            });
            debtor.amount = Math.round((debtor.amount - transfer) * 100) / 100;
            creditor.amount = Math.round((creditor.amount - transfer) * 100) / 100;
        }

        if (debtor.amount <= 0.005) dIdx++;
        if (creditor.amount <= 0.005) cIdx++;
    }

    return transactions;
}

function renderPayerInputs(grandTotal) {
    if (!payerInputsContainer) return;
    payerInputsContainer.innerHTML = '';

    if (state.people.length === 0) {
        payerInputsContainer.innerHTML = `<p class="empty-state">${t('empty_people')}</p>`;
        if (paidTotalPill) paidTotalPill.textContent = `${t('paid_total_label')} RM 0.00`;
        if (paymentStatusBar) paymentStatusBar.style.display = 'none';
        return;
    }

    let totalPaid = 0;

    state.people.forEach(person => {
        totalPaid += person.amountPaid || 0;
        const row = document.createElement('div');
        row.className = 'payer-row';
        const initial = person.name.charAt(0).toUpperCase();

        let balanceHtml = '';
        if (person.balance > 0.005) {
            balanceHtml = `<span class="payer-balance-pill balance-positive">+RM ${person.balance.toFixed(2)} (${t('balance_gets_back')})</span>`;
        } else if (person.balance < -0.005) {
            balanceHtml = `<span class="payer-balance-pill balance-negative">-RM ${Math.abs(person.balance).toFixed(2)} (${t('balance_owes')})</span>`;
        } else {
            balanceHtml = `<span class="payer-balance-pill balance-zero">RM 0.00 (${t('balance_settled')})</span>`;
        }

        row.innerHTML = `
            <div class="payer-person">
                <span class="badge-avatar">${initial}</span>
                <div class="payer-person-info">
                    <span class="payer-name">${person.name}</span>
                    <span class="payer-debt-tag">${t('modal_final')} RM ${person.debt.toFixed(2)}</span>
                </div>
            </div>
            <div class="payer-controls">
                <div class="payer-input-wrap">
                    <span class="currency-tag">RM</span>
                    <input type="number" class="glass-input payer-input" data-person-id="${person.id}" value="${person.amountPaid > 0 ? person.amountPaid.toFixed(2) : ''}" placeholder="0.00" min="0" step="0.01">
                </div>
                <button type="button" class="btn-paid-full" title="${t('paid_in_full')}">${t('paid_in_full')}</button>
                ${balanceHtml}
            </div>
        `;

        const input = row.querySelector('.payer-input');
        input.addEventListener('input', () => {
            const val = Math.max(0, parseFloat(input.value) || 0);
            person.amountPaid = Math.round(val * 100) / 100;
            saveToStorage();
            updateBalancesAndSettlementLive(grandTotal);
        });

        input.addEventListener('change', () => {
            const val = Math.max(0, parseFloat(input.value) || 0);
            person.amountPaid = Math.round(val * 100) / 100;
            saveToStorage();
            recalculateAndRender();
        });

        const btnFull = row.querySelector('.btn-paid-full');
        btnFull.addEventListener('click', () => {
            state.people.forEach(p => {
                if (p.id === person.id) {
                    p.amountPaid = Math.round(grandTotal * 100) / 100;
                } else {
                    p.amountPaid = 0;
                }
            });
            saveToStorage();
            recalculateAndRender();
            showToast(`${person.name}: ${t('toast_payment_updated')}`, 'info');
        });

        payerInputsContainer.appendChild(row);
    });

    if (paidTotalPill) {
        paidTotalPill.textContent = `${t('paid_total_label')} RM ${totalPaid.toFixed(2)}`;
    }

    updatePaymentStatusBar(totalPaid, grandTotal);
}

function updateBalancesAndSettlementLive(grandTotal) {
    const transactions = calculateSettlements(grandTotal);
    let totalPaid = 0;

    state.people.forEach(p => {
        totalPaid += p.amountPaid || 0;
        const inputEl = payerInputsContainer ? payerInputsContainer.querySelector(`[data-person-id="${p.id}"]`) : null;
        if (inputEl) {
            const row = inputEl.closest('.payer-row');
            if (row) {
                const pill = row.querySelector('.payer-balance-pill');
                if (pill) {
                    if (p.balance > 0.005) {
                        pill.className = 'payer-balance-pill balance-positive';
                        pill.textContent = `+RM ${p.balance.toFixed(2)} (${t('balance_gets_back')})`;
                    } else if (p.balance < -0.005) {
                        pill.className = 'payer-balance-pill balance-negative';
                        pill.textContent = `-RM ${Math.abs(p.balance).toFixed(2)} (${t('balance_owes')})`;
                    } else {
                        pill.className = 'payer-balance-pill balance-zero';
                        pill.textContent = `RM 0.00 (${t('balance_settled')})`;
                    }
                }
            }
        }
    });

    if (paidTotalPill) {
        paidTotalPill.textContent = `${t('paid_total_label')} RM ${totalPaid.toFixed(2)}`;
    }

    updatePaymentStatusBar(totalPaid, grandTotal);
    renderSettlementUI(transactions, grandTotal);
    renderDebtCards();
}

function updatePaymentStatusBar(totalPaid, grandTotal) {
    if (!paymentStatusBar) return;
    if (state.items.length > 0) {
        paymentStatusBar.style.display = 'flex';
        const diff = Math.round((totalPaid - grandTotal) * 100) / 100;
        if (Math.abs(diff) < 0.01) {
            paymentStatusBar.className = 'payment-status-bar matched';
            paymentStatusBar.innerHTML = `<span>${t('status_exact')}</span> <strong>RM ${grandTotal.toFixed(2)}</strong>`;
        } else if (diff < -0.01) {
            paymentStatusBar.className = 'payment-status-bar unmatched';
            paymentStatusBar.innerHTML = `<span>${t('status_remaining')}</span> <strong>RM ${Math.abs(diff).toFixed(2)} (${t('paid_total_label')} RM ${totalPaid.toFixed(2)} / RM ${grandTotal.toFixed(2)})</strong>`;
        } else {
            paymentStatusBar.className = 'payment-status-bar unmatched';
            paymentStatusBar.innerHTML = `<span>${t('status_overpaid')}</span> <strong>+RM ${diff.toFixed(2)}</strong>`;
        }
    } else {
        paymentStatusBar.style.display = 'none';
    }
}

function renderSettlementUI(transactions, grandTotal) {
    if (!settlementContainer) return;
    settlementContainer.innerHTML = '';

    const count = transactions.length;
    if (settlementCountPill) {
        settlementCountPill.textContent = `${count} ${count === 1 ? 'transfer' : 'transfers'}`;
    }

    const totalPaid = state.people.reduce((sum, p) => sum + (p.amountPaid || 0), 0);

    if (state.people.length === 0 || state.items.length === 0) {
        settlementContainer.innerHTML = `<p class="empty-state">${t('settlement_no_payments')}</p>`;
        return;
    }

    if (totalPaid === 0) {
        settlementContainer.innerHTML = `<p class="empty-state">${t('settlement_no_payments')}</p>`;
        return;
    }

    if (transactions.length === 0) {
        settlementContainer.innerHTML = `
            <div class="settlement-success-box">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>
                <span>${t('settlement_all_settled')}</span>
            </div>
        `;
        return;
    }

    transactions.forEach(tr => {
        const card = document.createElement('div');
        card.className = 'settlement-card';
        const fromInitial = tr.from.charAt(0).toUpperCase();
        const toInitial = tr.to.charAt(0).toUpperCase();

        card.innerHTML = `
            <div class="settlement-payer">
                <span class="badge-avatar">${fromInitial}</span>
                <span>${tr.from}</span>
            </div>
            <div class="settlement-arrow-box">
                <span>${t('needs_to_pay')}</span>
                <span class="settlement-amount">RM ${tr.amount.toFixed(2)}</span>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="settlement-arrow-icon"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
            </div>
            <div class="settlement-receiver">
                <span>${tr.to}</span>
                <span class="badge-avatar recipient">${toInitial}</span>
            </div>
        `;
        settlementContainer.appendChild(card);
    });
}

// -------------------------------------------------------------
// BUYERS BREAKDOWN VIEW
// -------------------------------------------------------------
function renderBuyersBreakdown() {
    if (!buyersBreakdownList) return;
    buyersBreakdownList.innerHTML = '';

    if (state.people.length === 0 || state.items.length === 0) {
        if (emptyBuyersState) emptyBuyersState.style.display = 'flex';
        return;
    }

    if (emptyBuyersState) emptyBuyersState.style.display = 'none';

    state.people.forEach(person => {
        const card = document.createElement('div');
        card.className = 'buyer-card open';

        const personItems = state.items.filter(i => i.sharedBy.includes(person.id));
        const itemCount = personItems.length;
        const initial = person.name.charAt(0).toUpperCase();

        const extraShare = person.debt - person.subtotal;
        let extraShareHtml = '';
        if (Math.abs(extraShare) > 0.005) {
            const prefix = extraShare >= 0 ? '+RM ' : '-RM ';
            extraShareHtml = `
                <div class="buyer-item-row" style="color:var(--text-muted); font-size:12px;">
                    <span>${t('tax_fee_share')}</span>
                    <span>${prefix}${Math.abs(extraShare).toFixed(2)}</span>
                </div>
            `;
        }

        let itemsHtml = '';
        if (itemCount === 0) {
            itemsHtml = `<div class="empty-state">${t('no_items_bought')}</div>`;
        } else {
            itemsHtml = personItems.map(item => {
                const myShare = item.price / item.sharedBy.length;
                return `
                    <div class="buyer-item-row">
                        <div>
                            <div class="buyer-item-name">${item.name}</div>
                            <div class="buyer-item-split-hint">1/${item.sharedBy.length} ${t('shared_by')} (RM ${item.price.toFixed(2)})</div>
                        </div>
                        <div class="buyer-item-price">RM ${myShare.toFixed(2)}</div>
                    </div>
                `;
            }).join('');
        }

        card.innerHTML = `
            <div class="buyer-header">
                <div class="buyer-info">
                    <div class="buyer-avatar">${initial}</div>
                    <div class="buyer-name-group">
                        <span class="buyer-name">${person.name}</span>
                        <span class="buyer-item-count">${itemCount} ${itemCount === 1 ? t('item_count') : t('items_count')}</span>
                    </div>
                </div>
                <div class="buyer-right">
                    <span class="buyer-due">RM ${person.debt.toFixed(2)}</span>
                    <span class="buyer-chevron">▼</span>
                </div>
            </div>
            <div class="buyer-items-detail">
                ${itemsHtml}
                ${extraShareHtml}
                <div class="buyer-action-row">
                    <button type="button" class="buyer-mini-btn btn-view-profile">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                        <span>${t('profile_btn')}</span>
                    </button>
                    <button type="button" class="buyer-mini-btn btn-copy-single">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
                        <span>${t('copy_buyer_bill')}</span>
                    </button>
                    <button type="button" class="buyer-mini-btn btn-wa-single">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="M12.031 2c-5.508 0-9.986 4.477-9.986 9.984 0 1.76.459 3.481 1.332 5.003L2 22l5.176-1.357c1.469.801 3.125 1.225 4.855 1.225 5.508 0 9.986-4.477 9.986-9.984 0-5.507-4.478-9.984-9.986-9.984zm5.795 14.137c-.244.685-1.42 1.34-1.956 1.398-.519.057-1.196.082-1.93-.153-1.644-.526-3.84-2.28-4.992-3.877-1.258-1.745-1.408-2.617-1.408-3.327 0-.756.326-1.464.733-1.872.244-.244.53-.306.708-.306.177 0 .354.004.51.011.168.008.39-.063.61.465.228.547.781 1.905.85 2.045.068.14.114.306.023.491-.092.186-.138.303-.274.464-.137.162-.29.362-.414.485-.138.138-.282.288-.122.563.161.275.714 1.176 1.534 1.906 1.054.939 1.942 1.23 2.217 1.368.275.137.436.115.597-.07.161-.184.688-.801.871-1.077.184-.275.367-.23.611-.137.244.092 1.554.733 1.821.868.267.136.446.204.513.318.069.115.069.664-.175 1.349z"/></svg>
                        <span>${t('wa_buyer_bill')}</span>
                    </button>
                </div>
            </div>
        `;

        // Toggle card open/collapse
        const header = card.querySelector('.buyer-header');
        header.addEventListener('click', () => {
            card.classList.toggle('open');
        });

        // View profile
        const viewProfileBtn = card.querySelector('.btn-view-profile');
        if (viewProfileBtn) {
            viewProfileBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                openProfileModal(person.id);
            });
        }

        // Copy single buyer bill
        const copyBtn = card.querySelector('.btn-copy-single');
        copyBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            copySingleBuyerBill(person);
        });

        // WhatsApp single buyer bill
        const waBtn = card.querySelector('.btn-wa-single');
        waBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            waSingleBuyerBill(person);
        });

        buyersBreakdownList.appendChild(card);
    });
}

function generateSingleBuyerText(person) {
    const personItems = state.items.filter(i => i.sharedBy.includes(person.id));
    if (personItems.length === 0) return null;

    let text = `👤 *${person.name}'s Bill Breakdown*\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `📦 *${t('profile_sec_a_title')}:*\n`;
    personItems.forEach(item => {
        const share = item.price / item.sharedBy.length;
        text += `• ${item.name}: RM ${share.toFixed(2)} (1/${item.sharedBy.length} ${t('shared_by')} RM ${item.price.toFixed(2)})\n`;
    });
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `${t('modal_subtotal')} RM ${person.subtotal.toFixed(2)}\n`;

    const extraShare = person.debt - person.subtotal;
    if (Math.abs(extraShare) > 0.005) {
        text += `${t('tax_fee_share')} ${extraShare >= 0 ? '+RM ' : '-RM '}${Math.abs(extraShare).toFixed(2)}\n`;
    }
    text += `💰 *${t('modal_final')} RM ${person.debt.toFixed(2)}*\n`;

    // Settlement Section B info
    const paid = person.amountPaid || 0;
    const bal = person.balance || 0;
    text += `💳 ${t('upfront_paid')} RM ${paid.toFixed(2)}\n`;
    if (bal > 0.005) {
        text += `⚖️ ${t('net_balance')} +RM ${bal.toFixed(2)} (${t('balance_gets_back')})\n`;
    } else if (bal < -0.005) {
        text += `⚖️ ${t('net_balance')} -RM ${Math.abs(bal).toFixed(2)} (${t('balance_owes')})\n`;
    } else {
        text += `⚖️ ${t('net_balance')} RM 0.00 (${t('balance_settled')})\n`;
    }

    const grandTotal = state.people.reduce((acc, p) => acc + p.debt, 0);
    const transactions = calculateSettlements(grandTotal);

    const myDebts = transactions.filter(tr => tr.fromId === person.id);
    const myReceivables = transactions.filter(tr => tr.toId === person.id);

    if (myDebts.length > 0) {
        text += `\n🔄 *${t('profile_sec_b_title')}:*\n`;
        myDebts.forEach(tr => {
            text += `👉 ${t('needs_to_pay_who')} *${tr.to}*: RM ${tr.amount.toFixed(2)}\n`;
        });
    } else if (myReceivables.length > 0) {
        text += `\n📥 *${t('profile_sec_b_title')}:*\n`;
        myReceivables.forEach(tr => {
            text += `✅ *${tr.from}* ${t('will_pay_you')}: RM ${tr.amount.toFixed(2)}\n`;
        });
    }

    text += `\n_${t('receipt_footer')}_`;
    return text;
}

function copySingleBuyerBill(person) {
    const text = generateSingleBuyerText(person);
    if (!text) {
        showToast(t('no_items_bought'), 'error');
        return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(() => {
            showToast(`${person.name}: ${t('buyer_bill_copied')}`, 'success');
        }).catch(() => {
            fallbackCopy(text);
        });
    } else {
        fallbackCopy(text);
    }
}

function waSingleBuyerBill(person) {
    const text = generateSingleBuyerText(person);
    if (!text) {
        showToast(t('no_items_bought'), 'error');
        return;
    }
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
}

// -------------------------------------------------------------
// DETAILED USER PROFILE MODAL (REQUIREMENT 6)
// -------------------------------------------------------------
function openProfileModal(personId) {
    const person = state.people.find(p => p.id === personId);
    if (!person || !profileModal) return;

    activeProfilePersonId = personId;

    if (profileName) profileName.textContent = person.name;
    if (profileAvatar) profileAvatar.textContent = person.name.charAt(0).toUpperCase();

    // SECTION A: Purchase History
    if (profileItemsList) {
        profileItemsList.innerHTML = '';
        const personItems = state.items.filter(i => i.sharedBy.includes(personId));

        if (personItems.length === 0) {
            profileItemsList.innerHTML = `<li class="empty-state" style="padding:12px; font-size:13px;">${t('no_items_in_profile')}</li>`;
        } else {
            personItems.forEach(item => {
                const splitPrice = item.price / item.sharedBy.length;
                const li = document.createElement('li');
                li.className = 'profile-item-row';
                li.innerHTML = `
                    <div class="profile-item-details">
                        <span class="profile-item-name">${item.name}</span>
                        <span class="profile-item-fraction">1/${item.sharedBy.length} ${t('share_of')} RM ${item.price.toFixed(2)}</span>
                    </div>
                    <strong class="profile-item-price">RM ${splitPrice.toFixed(2)}</strong>
                `;
                profileItemsList.appendChild(li);
            });
        }
    }

    if (profileSubtotalVal) profileSubtotalVal.textContent = `RM ${person.subtotal.toFixed(2)}`;

    const extraShare = person.debt - person.subtotal;
    if (profileTaxLine && profileExtraVal) {
        if (Math.abs(extraShare) > 0.005) {
            profileTaxLine.style.display = 'flex';
            profileExtraVal.textContent = (extraShare >= 0 ? '+RM ' : '-RM ') + Math.abs(extraShare).toFixed(2);
        } else {
            profileTaxLine.style.display = 'none';
        }
    }

    if (profileFinalVal) profileFinalVal.textContent = `RM ${person.debt.toFixed(2)}`;

    // SECTION B: Settlement / Who to Pay
    const paid = person.amountPaid || 0;
    if (profilePaidVal) profilePaidVal.textContent = `RM ${paid.toFixed(2)}`;

    if (profileBalanceVal) {
        if (person.balance > 0.005) {
            profileBalanceVal.className = 'payer-balance-pill balance-positive';
            profileBalanceVal.textContent = `+RM ${person.balance.toFixed(2)} (${t('balance_gets_back')})`;
        } else if (person.balance < -0.005) {
            profileBalanceVal.className = 'payer-balance-pill balance-negative';
            profileBalanceVal.textContent = `-RM ${Math.abs(person.balance).toFixed(2)} (${t('balance_owes')})`;
        } else {
            profileBalanceVal.className = 'payer-balance-pill balance-zero';
            profileBalanceVal.textContent = `RM 0.00 (${t('balance_settled')})`;
        }
    }

    // Direct transfers for this specific person
    if (profileSettlementList) {
        profileSettlementList.innerHTML = '';
        const grandTotal = state.people.reduce((acc, p) => acc + p.debt, 0);
        const transactions = calculateSettlements(grandTotal);

        const myDebts = transactions.filter(tr => tr.fromId === person.id);
        const myReceivables = transactions.filter(tr => tr.toId === person.id);

        if (myDebts.length > 0) {
            myDebts.forEach(tr => {
                const item = document.createElement('div');
                item.className = 'profile-settlement-item owe';
                item.innerHTML = `
                    <div class="profile-settlement-icon">👉</div>
                    <div class="profile-settlement-info">
                        <span class="profile-settlement-label">${t('needs_to_pay_who')} <strong>${tr.to}</strong></span>
                        <span class="profile-settlement-amount text-danger">RM ${tr.amount.toFixed(2)}</span>
                    </div>
                `;
                profileSettlementList.appendChild(item);
            });
        } else if (myReceivables.length > 0) {
            myReceivables.forEach(tr => {
                const item = document.createElement('div');
                item.className = 'profile-settlement-item receive';
                item.innerHTML = `
                    <div class="profile-settlement-icon">📥</div>
                    <div class="profile-settlement-info">
                        <span class="profile-settlement-label"><strong>${tr.from}</strong> ${t('will_pay_you')}</span>
                        <span class="profile-settlement-amount text-success">RM ${tr.amount.toFixed(2)}</span>
                    </div>
                `;
                profileSettlementList.appendChild(item);
            });
        } else {
            profileSettlementList.innerHTML = `
                <div class="profile-settlement-item settled">
                    <div class="profile-settlement-icon">✅</div>
                    <div class="profile-settlement-info">
                        <span class="profile-settlement-label">${t('profile_all_settled')}</span>
                    </div>
                </div>
            `;
        }
    }

    profileModal.style.display = 'flex';
}

function closeProfileModal() {
    if (profileModal) profileModal.style.display = 'none';
    activeProfilePersonId = null;
}

if (btnCloseProfileModal) btnCloseProfileModal.addEventListener('click', closeProfileModal);
if (btnDismissProfileModal) btnDismissProfileModal.addEventListener('click', closeProfileModal);
if (profileModal) {
    profileModal.addEventListener('click', (e) => {
        if (e.target === profileModal) closeProfileModal();
    });
}

// Profile Modal Share Actions
if (btnProfileCopy) {
    btnProfileCopy.addEventListener('click', () => {
        if (!activeProfilePersonId) return;
        const person = state.people.find(p => p.id === activeProfilePersonId);
        if (person) copySingleBuyerBill(person);
    });
}

if (btnProfileWa) {
    btnProfileWa.addEventListener('click', () => {
        if (!activeProfilePersonId) return;
        const person = state.people.find(p => p.id === activeProfilePersonId);
        if (person) waSingleBuyerBill(person);
    });
}

// Fallback alias for existing breakdown clicks
const openPersonBreakdown = openProfileModal;
function closeModal() {
    if (modalBreakdown) modalBreakdown.style.display = 'none';
}
if (btnCloseModal) btnCloseModal.addEventListener('click', closeModal);
if (btnDismissModal) btnDismissModal.addEventListener('click', closeModal);

document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
        if (profileModal && profileModal.style.display === 'flex') closeProfileModal();
        if (modalBreakdown && modalBreakdown.style.display === 'flex') closeModal();
    }
});

// -------------------------------------------------------------
// RECEIPT FORMATTING FOR EXPORT (STEP 5)
// -------------------------------------------------------------
function generateReceiptText() {
    if (state.items.length === 0) return null;

    let subtotal = 0;
    state.items.forEach(i => subtotal += i.price);

    const taxTotal = subtotal * (state.extras.taxPercent / 100);
    const serviceTotal = subtotal * (state.extras.servicePercent / 100);
    const discountTotal = Math.min(state.extras.discountAmount || 0, subtotal + taxTotal + serviceTotal);
    const grandTotal = Math.max(0, subtotal + taxTotal + serviceTotal - discountTotal);

    let text = `${t('receipt_header')}\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `${t('receipt_items_title')}\n`;

    state.items.forEach(item => {
        text += `• ${item.name}: RM ${item.price.toFixed(2)} (${item.sharedBy.length} ${t('pays')})\n`;
    });

    text += `━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `💵 ${t('subtotal')} RM ${subtotal.toFixed(2)}\n`;

    if (taxTotal > 0) {
        text += `📑 ${t('label_tax')} (${state.extras.taxPercent}%): +RM ${taxTotal.toFixed(2)}\n`;
    }
    if (serviceTotal > 0) {
        text += `🛎️ ${t('label_service')} (${state.extras.servicePercent}%): +RM ${serviceTotal.toFixed(2)}\n`;
    }
    if (discountTotal > 0) {
        text += `🏷️ ${t('label_discount')}: -RM ${discountTotal.toFixed(2)}\n`;
    }

    text += `💰 *${t('total_receipt')} RM ${grandTotal.toFixed(2)}*\n\n`;
    text += `${t('receipt_breakdown_title')}\n`;

    state.people.forEach(p => {
        if (p.debt > 0) {
            text += `👤 *${p.name}*: RM ${p.debt.toFixed(2)}\n`;
        }
    });

    // Check if any payments were recorded
    const totalPaid = state.people.reduce((sum, p) => sum + (p.amountPaid || 0), 0);
    if (totalPaid > 0) {
        text += `\n━━━━━━━━━━━━━━━━━━━━━\n`;
        text += `${t('receipt_payments_title')}\n`;
        state.people.forEach(p => {
            const paid = p.amountPaid || 0;
            const bal = p.balance || 0;
            let balDesc = '';
            if (bal > 0.005) balDesc = ` (+RM ${bal.toFixed(2)} ${t('balance_gets_back')})`;
            else if (bal < -0.005) balDesc = ` (-RM ${Math.abs(bal).toFixed(2)} ${t('balance_owes')})`;
            else balDesc = ` (${t('balance_settled')})`;
            text += `• ${p.name}: RM ${paid.toFixed(2)}${balDesc}\n`;
        });

        const transactions = calculateSettlements(grandTotal);
        text += `\n${t('receipt_settlement_title')}\n`;
        if (transactions.length > 0) {
            transactions.forEach(tr => {
                text += `👉 *${tr.from}* ${t('needs_to_pay')} *${tr.to}* RM ${tr.amount.toFixed(2)}\n`;
            });
        } else {
            text += `${t('receipt_all_settled')}\n`;
        }
    }

    text += `\n_${t('receipt_footer')}_`;
    return text;
}

if (btnWa) {
    btnWa.addEventListener('click', () => {
        const text = generateReceiptText();
        if (!text) {
            showToast(t('toast_no_items'), 'error');
            return;
        }
        const encoded = encodeURIComponent(text);
        window.open(`https://wa.me/?text=${encoded}`, '_blank');
    });
}

if (btnCopy) {
    btnCopy.addEventListener('click', () => {
        const text = generateReceiptText();
        if (!text) {
            showToast(t('toast_no_items'), 'error');
            return;
        }

        if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(text).then(() => {
                showToast(t('toast_copied'), 'success');
            }).catch(() => {
                fallbackCopy(text);
            });
        } else {
            fallbackCopy(text);
        }
    });
}

function fallbackCopy(text) {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.select();
    try {
        document.execCommand('copy');
        showToast(t('toast_copied'), 'success');
    } catch (e) {
        showToast('Copy failed, please copy manually.', 'error');
    }
    document.body.removeChild(textArea);
}

if (btnQr && qrImage && qrContainer) {
    btnQr.addEventListener('click', () => {
        const text = generateReceiptText();
        if (!text) {
            showToast(t('toast_no_items'), 'error');
            return;
        }

        const encoded = encodeURIComponent(text);
        qrImage.src = `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encoded}&margin=10`;
        qrContainer.style.display = 'block';
        qrContainer.scrollIntoView({ behavior: 'smooth' });
    });
}

if (btnCloseQr && qrContainer) {
    btnCloseQr.addEventListener('click', () => {
        qrContainer.style.display = 'none';
    });
}

// Reset All
if (btnReset) {
    btnReset.addEventListener('click', () => {
        if (confirm(t('toast_reset_confirm'))) {
            state.people = [];
            state.items = [];
            state.extras = { taxPercent: 0, servicePercent: 0, discountAmount: 0 };
            state.personIdCounter = 1;
            state.itemIdCounter = 1;

            if (inputTax) inputTax.value = '0';
            if (inputService) inputService.value = '0';
            if (inputDiscount) inputDiscount.value = '0';
            if (qrContainer) qrContainer.style.display = 'none';

            saveToStorage();
            renderPeopleUI();
            recalculateAndRender();
            showToast('All data has been reset.', 'info');
        }
    });
}

// Tab Switching (By Items vs By Buyer)
if (tabBtnItems && tabBtnBuyers && viewItems && viewBuyers) {
    tabBtnItems.addEventListener('click', () => {
        tabBtnItems.classList.add('active');
        tabBtnBuyers.classList.remove('active');
        viewItems.style.display = 'block';
        viewBuyers.style.display = 'none';
    });

    tabBtnBuyers.addEventListener('click', () => {
        tabBtnBuyers.classList.add('active');
        tabBtnItems.classList.remove('active');
        viewBuyers.style.display = 'block';
        viewItems.style.display = 'none';
        renderBuyersBreakdown();
    });
}

// -------------------------------------------------------------
// NAVIGATION BAR (CALCULATOR VS CLOUD DASHBOARD)
// -------------------------------------------------------------
function switchAppTab(tab) {
    currentAppTab = tab;
    if (tab === 'calculator') {
        if (navBtnCalculator) navBtnCalculator.classList.add('active');
        if (navBtnDashboard) navBtnDashboard.classList.remove('active');
        if (viewCalculator) viewCalculator.style.display = 'block';
        if (viewDashboard) viewDashboard.style.display = 'none';
    } else if (tab === 'dashboard') {
        if (navBtnDashboard) navBtnDashboard.classList.add('active');
        if (navBtnCalculator) navBtnCalculator.classList.remove('active');
        if (viewDashboard) viewDashboard.style.display = 'block';
        if (viewCalculator) viewCalculator.style.display = 'none';
        loadCloudData();
    }
}

if (navBtnCalculator) {
    navBtnCalculator.addEventListener('click', () => switchAppTab('calculator'));
}

if (navBtnDashboard) {
    navBtnDashboard.addEventListener('click', () => switchAppTab('dashboard'));
}

// -------------------------------------------------------------
// AUTHENTICATION LOGIC & GUEST MODE
// -------------------------------------------------------------
function setupAuthEvents() {
    // Tab toggling: Sign In vs Register
    if (tabLogin && tabSignup) {
        tabLogin.addEventListener('click', () => {
            authMode = 'login';
            tabLogin.classList.add('active');
            tabSignup.classList.remove('active');
            if (fieldDisplayName) fieldDisplayName.style.display = 'none';
            if (authBtnText) authBtnText.textContent = t('auth_btn_login');
            hideAuthAlert();
        });

        tabSignup.addEventListener('click', () => {
            authMode = 'signup';
            tabSignup.classList.add('active');
            tabLogin.classList.remove('active');
            if (fieldDisplayName) fieldDisplayName.style.display = 'block';
            if (authBtnText) authBtnText.textContent = t('auth_btn_signup');
            hideAuthAlert();
        });
    }

    // Guest Mode Bypass
    if (btnGuestMode) {
        btnGuestMode.addEventListener('click', () => {
            isGuestMode = true;
            if (authScreen) authScreen.style.display = 'none';
            if (mainAppContent) mainAppContent.style.display = 'block';
            if (userHeaderProfile) userHeaderProfile.style.display = 'none';
            if (btnHeaderLogin) btnHeaderLogin.style.display = 'inline-flex';
            showToast(t('auth_guest_welcome'), 'info');
        });
    }

    // Header Login button (when in guest mode)
    if (btnHeaderLogin) {
        btnHeaderLogin.addEventListener('click', () => {
            if (authScreen) authScreen.style.display = 'flex';
            if (mainAppContent) mainAppContent.style.display = 'none';
            if (btnHeaderLogin) btnHeaderLogin.style.display = 'none';
        });
    }

    // Log Out
    if (btnLogout) {
        btnLogout.addEventListener('click', async () => {
            if (supabaseClient) {
                await supabaseClient.auth.signOut();
            }
            handleUserSignedOut();
            showToast(t('auth_logged_out'), 'info');
        });
    }

    // Auth Form Submission (Sign In or Sign Up)
    if (authForm) {
        authForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            if (!supabaseClient) {
                showAuthAlert('Supabase client is not loaded. Please check your internet connection.', 'error');
                return;
            }

            const email = inputAuthEmail.value.trim();
            const password = inputAuthPassword.value;
            const displayName = inputDisplayName ? inputDisplayName.value.trim() : '';

            hideAuthAlert();
            setAuthLoading(true);

            try {
                if (authMode === 'signup') {
                    const { data, error } = await supabaseClient.auth.signUp({
                        email: email,
                        password: password,
                        options: {
                            data: {
                                display_name: displayName || email.split('@')[0]
                            }
                        }
                    });

                    if (error) throw error;

                    if (data && data.user) {
                        // Insert/Upsert into public.users profile table
                        await supabaseClient.from('users').upsert({
                            id: data.user.id,
                            email: email,
                            display_name: displayName || email.split('@')[0]
                        });

                        showToast(t('auth_signup_success'), 'success');
                        handleUserSignedIn(data.user);
                    }
                } else {
                    // Sign In
                    const { data, error } = await supabaseClient.auth.signInWithPassword({
                        email: email,
                        password: password
                    });

                    if (error) throw error;

                    if (data && data.user) {
                        showToast(t('auth_login_success'), 'success');
                        handleUserSignedIn(data.user);
                    }
                }
            } catch (err) {
                console.error('Auth error:', err);
                showAuthAlert(err.message || 'Authentication failed. Please verify credentials.', 'error');
            } finally {
                setAuthLoading(false);
            }
        });
    }
}

function showAuthAlert(msg, type = 'error') {
    if (!authAlert) return;
    authAlert.textContent = msg;
    authAlert.className = `auth-alert ${type}`;
    authAlert.style.display = 'block';
}

function hideAuthAlert() {
    if (!authAlert) return;
    authAlert.style.display = 'none';
}

function setAuthLoading(isLoading) {
    if (!btnAuthSubmit) return;
    btnAuthSubmit.disabled = isLoading;
    if (isLoading) {
        btnAuthSubmit.style.opacity = '0.7';
    } else {
        btnAuthSubmit.style.opacity = '1';
    }
}

function handleUserSignedIn(user) {
    currentUser = user;
    isGuestMode = false;

    // Display user profile in header
    const name = (user.user_metadata && user.user_metadata.display_name) || user.email.split('@')[0];
    if (headerUserName) headerUserName.textContent = name;
    if (headerUserEmail) headerUserEmail.textContent = user.email;
    if (headerUserAvatar) headerUserAvatar.textContent = name.charAt(0).toUpperCase();

    if (userHeaderProfile) userHeaderProfile.style.display = 'flex';
    if (btnHeaderLogin) btnHeaderLogin.style.display = 'none';

    // Transition views
    if (authScreen) authScreen.style.display = 'none';
    if (mainAppContent) mainAppContent.style.display = 'block';

    // If shoppers list is empty, default user as first shopper
    if (state.people.length === 0) {
        state.people.push({
            id: state.personIdCounter++,
            name: name,
            debt: 0,
            subtotal: 0,
            amountPaid: 0,
            balance: 0
        });
        saveToStorage();
        renderPeopleUI();
        recalculateAndRender();
    }

    // Load user's cloud debts & bills
    loadCloudData();
}

function handleUserSignedOut() {
    currentUser = null;
    isGuestMode = false;

    if (userHeaderProfile) userHeaderProfile.style.display = 'none';
    if (btnHeaderLogin) btnHeaderLogin.style.display = 'none';
    if (mainAppContent) mainAppContent.style.display = 'none';
    if (authScreen) authScreen.style.display = 'flex';
    if (navDebtCount) navDebtCount.style.display = 'none';

    // Reset password field
    if (inputAuthPassword) inputAuthPassword.value = '';
}

async function initAuth() {
    setupAuthEvents();

    if (!supabaseClient) {
        console.warn('Supabase client unavailable. Running in offline/guest mode.');
        if (authScreen) authScreen.style.display = 'none';
        if (mainAppContent) mainAppContent.style.display = 'block';
        return;
    }

    // Check active session
    try {
        const { data: { session } } = await supabaseClient.auth.getSession();
        if (session && session.user) {
            handleUserSignedIn(session.user);
        } else {
            // Unauthenticated state: show auth modal
            if (authScreen) authScreen.style.display = 'flex';
            if (mainAppContent) mainAppContent.style.display = 'none';
        }
    } catch (e) {
        console.error('Session retrieval error:', e);
        if (authScreen) authScreen.style.display = 'flex';
        if (mainAppContent) mainAppContent.style.display = 'none';
    }

    // Subscribe to Auth State Changes
    supabaseClient.auth.onAuthStateChange((event, session) => {
        if (event === 'SIGNED_IN' && session && session.user) {
            handleUserSignedIn(session.user);
        } else if (event === 'SIGNED_OUT') {
            handleUserSignedOut();
        }
    });
}

// -------------------------------------------------------------
// SUPABASE CLOUD SYNC & DASHBOARD (REQUIREMENTS 3 & 4)
// -------------------------------------------------------------
async function saveBillToCloud() {
    if (!currentUser) {
        showToast('Please sign in or register to sync your bills with Supabase cloud!', 'error');
        if (authScreen) authScreen.style.display = 'flex';
        if (mainAppContent) mainAppContent.style.display = 'none';
        return;
    }

    if (state.items.length === 0) {
        showToast(t('toast_no_items'), 'error');
        return;
    }

    if (!btnSaveCloud) return;
    const originalText = btnSaveCloud.innerHTML;
    btnSaveCloud.disabled = true;
    btnSaveCloud.innerHTML = `<span>Saving...</span>`;

    try {
        let subtotal = 0;
        state.items.forEach(i => subtotal += i.price);
        const taxTotal = subtotal * (state.extras.taxPercent / 100);
        const serviceTotal = subtotal * (state.extras.servicePercent / 100);
        const discountTotal = Math.min(state.extras.discountAmount || 0, subtotal + taxTotal + serviceTotal);
        const grandTotal = Math.max(0, subtotal + taxTotal + serviceTotal - discountTotal);

        const currentUserName = (currentUser.user_metadata && currentUser.user_metadata.display_name)
            || currentUser.email.split('@')[0];

        // 1. Insert into public.bills
        const { data: billData, error: billError } = await supabaseClient
            .from('bills')
            .insert([{
                created_by: currentUser.id,
                title: `Bill ${new Date().toLocaleDateString()}`,
                total_amount: grandTotal
            }])
            .select()
            .single();

        if (billError) throw billError;

        // 2. Insert into public.bill_items
        if (state.items.length > 0) {
            const billItems = state.items.map(item => {
                const names = item.sharedBy.map(id => {
                    const p = state.people.find(x => x.id === id);
                    return p ? p.name : String(id);
                });
                return {
                    bill_id: billData.id,
                    name: item.name,
                    price: item.price,
                    shared_by: names
                };
            });

            const { error: itemsError } = await supabaseClient
                .from('bill_items')
                .insert(billItems);

            if (itemsError) throw itemsError;
        }

        // 3. Insert Settlement Transfers into public.debts
        const transactions = calculateSettlements(grandTotal);
        if (transactions.length > 0) {
            const debtsToInsert = transactions.map(tr => {
                const isDebtorMe = tr.from.toLowerCase() === currentUserName.toLowerCase();
                const isCreditorMe = tr.to.toLowerCase() === currentUserName.toLowerCase();

                return {
                    bill_id: billData.id,
                    debtor_id: isDebtorMe ? currentUser.id : null,
                    debtor_name: tr.from,
                    creditor_id: isCreditorMe ? currentUser.id : (isDebtorMe ? null : currentUser.id),
                    creditor_name: tr.to,
                    amount: tr.amount,
                    status: 'pending'
                };
            });

            const { error: debtsError } = await supabaseClient
                .from('debts')
                .insert(debtsToInsert);

            if (debtsError) throw debtsError;
        }

        showToast(t('toast_bill_saved_cloud'), 'success');
        loadCloudData();
    } catch (err) {
        console.error('Error saving to Supabase:', err);
        showToast(err.message || 'Failed to save bill to cloud.', 'error');
    } finally {
        btnSaveCloud.disabled = false;
        btnSaveCloud.innerHTML = originalText;
    }
}

if (btnSaveCloud) {
    btnSaveCloud.addEventListener('click', saveBillToCloud);
}

async function loadCloudData() {
    if (!currentUser || !supabaseClient) return;

    try {
        const currentUserName = (currentUser.user_metadata && currentUser.user_metadata.display_name)
            || currentUser.email.split('@')[0];

        // Fetch all debts where user is involved
        const { data: debts, error: debtsErr } = await supabaseClient
            .from('debts')
            .select('*')
            .order('created_at', { ascending: false });

        if (debtsErr) throw debtsErr;
        cloudDebts = debts || [];

        // Fetch user's saved bills
        const { data: bills, error: billsErr } = await supabaseClient
            .from('bills')
            .select('*, bill_items(id, name, price)')
            .eq('created_by', currentUser.id)
            .order('created_at', { ascending: false });

        if (billsErr) throw billsErr;
        cloudBills = bills || [];

        renderCloudDashboard();
    } catch (err) {
        console.error('Error fetching cloud data:', err);
    }
}

if (btnRefreshDebts) {
    btnRefreshDebts.addEventListener('click', () => {
        loadCloudData();
        showToast('Debts synchronized with cloud.', 'info');
    });
}

function renderCloudDashboard() {
    if (!currentUser) return;

    const currentUserName = ((currentUser.user_metadata && currentUser.user_metadata.display_name)
        || currentUser.email.split('@')[0]).toLowerCase();

    // 1. Filter: Debts where user is CREDITOR (People owe me)
    const whoOwesMe = cloudDebts.filter(d => {
        const isCreditorId = d.creditor_id === currentUser.id;
        const isCreditorName = d.creditor_name && d.creditor_name.toLowerCase() === currentUserName;
        return (isCreditorId || isCreditorName) && d.debtor_id !== currentUser.id;
    });

    // 2. Filter: Debts where user is DEBTOR (I owe others)
    const iOwe = cloudDebts.filter(d => {
        const isDebtorId = d.debtor_id === currentUser.id;
        const isDebtorName = d.debtor_name && d.debtor_name.toLowerCase() === currentUserName;
        return (isDebtorId || isDebtorName) && d.creditor_id !== currentUser.id;
    });

    // 3. Calculate Totals (Pending only)
    const totalOwedToMe = whoOwesMe
        .filter(d => d.status === 'pending')
        .reduce((sum, d) => sum + parseFloat(d.amount || 0), 0);

    const totalIOwe = iOwe
        .filter(d => d.status === 'pending')
        .reduce((sum, d) => sum + parseFloat(d.amount || 0), 0);

    const netPosition = totalOwedToMe - totalIOwe;

    // Render Stat Cards
    if (statTotalIOwe) statTotalIOwe.textContent = `RM ${totalIOwe.toFixed(2)}`;
    if (statTotalOwedToMe) statTotalOwedToMe.textContent = `RM ${totalOwedToMe.toFixed(2)}`;
    if (statNetPosition) {
        const sign = netPosition >= 0 ? '+RM ' : '-RM ';
        statNetPosition.textContent = `${sign}${Math.abs(netPosition).toFixed(2)}`;
        if (netPosition >= 0) {
            statNetPosition.className = 'stat-number text-success';
        } else {
            statNetPosition.className = 'stat-number text-danger';
        }
    }

    // Update Nav Badge
    const pendingTotalCount = whoOwesMe.filter(d => d.status === 'pending').length
        + iOwe.filter(d => d.status === 'pending').length;

    if (navDebtCount) {
        if (pendingTotalCount > 0) {
            navDebtCount.textContent = pendingTotalCount;
            navDebtCount.style.display = 'inline-block';
        } else {
            navDebtCount.style.display = 'none';
        }
    }

    // 4. Render "People Who Owe Me" List
    if (listWhoOwesMe) {
        listWhoOwesMe.innerHTML = '';
        if (whoOwesMe.length === 0) {
            listWhoOwesMe.innerHTML = `<p class="empty-state">${t('no_one_owes_you')}</p>`;
        } else {
            whoOwesMe.forEach(debt => {
                const item = document.createElement('div');
                item.className = `cloud-debt-item ${debt.status === 'paid' ? 'paid-item' : ''}`;
                const initial = debt.debtor_name.charAt(0).toUpperCase();
                const isPaid = debt.status === 'paid';

                item.innerHTML = `
                    <div class="debt-item-user">
                        <span class="badge-avatar">${initial}</span>
                        <div>
                            <strong>${debt.debtor_name}</strong>
                            <div class="debt-item-date">${new Date(debt.created_at).toLocaleDateString()}</div>
                        </div>
                    </div>
                    <div class="debt-item-actions">
                        <span class="debt-item-amount text-success">RM ${parseFloat(debt.amount).toFixed(2)}</span>
                        <span class="debt-status-badge ${isPaid ? 'badge-paid' : 'badge-pending'}">
                            ${isPaid ? t('status_paid') : t('status_pending')}
                        </span>
                        <button type="button" class="glass-btn mini-btn btn-toggle-debt">
                            ${isPaid ? t('mark_pending') : t('mark_paid')}
                        </button>
                    </div>
                `;

                item.querySelector('.btn-toggle-debt').addEventListener('click', async () => {
                    await toggleDebtStatus(debt.id, isPaid ? 'pending' : 'paid');
                });

                listWhoOwesMe.appendChild(item);
            });
        }
    }

    // 5. Render "Debts I Owe to Others" List
    if (listIOwe) {
        listIOwe.innerHTML = '';
        if (iOwe.length === 0) {
            listIOwe.innerHTML = `<p class="empty-state">${t('you_owe_nothing')}</p>`;
        } else {
            iOwe.forEach(debt => {
                const item = document.createElement('div');
                item.className = `cloud-debt-item ${debt.status === 'paid' ? 'paid-item' : ''}`;
                const initial = debt.creditor_name.charAt(0).toUpperCase();
                const isPaid = debt.status === 'paid';

                item.innerHTML = `
                    <div class="debt-item-user">
                        <span class="badge-avatar recipient">${initial}</span>
                        <div>
                            <strong>${debt.creditor_name}</strong>
                            <div class="debt-item-date">${new Date(debt.created_at).toLocaleDateString()}</div>
                        </div>
                    </div>
                    <div class="debt-item-actions">
                        <span class="debt-item-amount text-danger">RM ${parseFloat(debt.amount).toFixed(2)}</span>
                        <span class="debt-status-badge ${isPaid ? 'badge-paid' : 'badge-pending'}">
                            ${isPaid ? t('status_paid') : t('status_pending')}
                        </span>
                    </div>
                `;
                listIOwe.appendChild(item);
            });
        }
    }

    // 6. Render Saved Cloud Bills History
    if (listCloudBills) {
        listCloudBills.innerHTML = '';
        if (cloudBillsCount) cloudBillsCount.textContent = `${cloudBills.length} bills`;

        if (cloudBills.length === 0) {
            listCloudBills.innerHTML = `<p class="empty-state">${t('no_cloud_bills')}</p>`;
        } else {
            cloudBills.forEach(bill => {
                const item = document.createElement('div');
                item.className = 'cloud-bill-row';
                const itemsCount = (bill.bill_items && bill.bill_items.length) || 0;

                item.innerHTML = `
                    <div class="bill-row-info">
                        <strong>${bill.title || 'Bill Split'}</strong>
                        <span class="bill-row-meta">${new Date(bill.created_at).toLocaleString()} • ${itemsCount} items</span>
                    </div>
                    <div class="bill-row-actions">
                        <strong class="bill-row-total">RM ${parseFloat(bill.total_amount).toFixed(2)}</strong>
                        <button type="button" class="icon-delete-btn btn-delete-cloud-bill" title="Delete bill">&times;</button>
                    </div>
                `;

                item.querySelector('.btn-delete-cloud-bill').addEventListener('click', async () => {
                    if (confirm(t('toast_confirm_delete_bill'))) {
                        await deleteCloudBill(bill.id);
                    }
                });

                listCloudBills.appendChild(item);
            });
        }
    }
}

async function toggleDebtStatus(debtId, newStatus) {
    if (!supabaseClient) return;
    try {
        const { error } = await supabaseClient
            .from('debts')
            .update({ status: newStatus })
            .eq('id', debtId);

        if (error) throw error;
        showToast(newStatus === 'paid' ? t('toast_debt_marked_paid') : t('toast_debt_marked_pending'), 'success');
        await loadCloudData();
    } catch (e) {
        console.error('Error toggling debt status:', e);
        showToast('Failed to update debt status.', 'error');
    }
}

async function deleteCloudBill(billId) {
    if (!supabaseClient) return;
    try {
        const { error } = await supabaseClient
            .from('bills')
            .delete()
            .eq('id', billId);

        if (error) throw error;
        showToast(t('toast_bill_deleted'), 'info');
        await loadCloudData();
    } catch (e) {
        console.error('Error deleting bill:', e);
        showToast('Failed to delete bill.', 'error');
    }
}

// -------------------------------------------------------------
// APP INITIALIZATION
// -------------------------------------------------------------
async function initApp() {
    loadFromStorage();

    // Populate extra fee inputs if restored
    if (state.extras) {
        if (inputTax) inputTax.value = state.extras.taxPercent || 0;
        if (inputService) inputService.value = state.extras.servicePercent || 0;
        if (inputDiscount) inputDiscount.value = state.extras.discountAmount || 0;
    }

    applyTheme(state.settings.darkMode);
    updateLanguageUI();
    renderPeopleUI();
    recalculateAndRender();

    // Initialize Supabase Full-Stack Authentication & Sync
    await initAuth();
}

// Start application
initApp();
